id: dns_pentesting
name: DNS Penetration Testing (Port 53)
description: Comprehensive DNS enumeration, zone transfer attacks, subdomain brute forcing, and cache poisoning based on HackTricks methodology
category: enumeration
risk_level: medium
batch_compatible: true

triggers:
  - id: trigger_dns_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [53, 5353] }
      protocol: { "$in": ["dns", "tcp", "udp"] }
    required_count: 1
    priority: 4
    description: Triggers when DNS service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: dns_banner_grab
    name: DNS Banner Grabbing and Fingerprinting
    description: Identify DNS server version and type
    order: 1
    timeout_seconds: 30
    commands:
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig version.bind CHAOS TXT @{host}"
        preferred: true
        notes: "Query BIND version (works on most BIND nameservers)"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -n --script '(default and *dns*) or fcrdns or dns-srv-enum or dns-random-txid or dns-random-srcport' {host} -p {port}"
        preferred: true
        notes: "Comprehensive DNS enumeration and vulnerability scanning"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sSU -p53 --script dns-nsid {host}"
        preferred: false
        notes: "DNS server fingerprinting via NSID"
        requires_elevation: false
      - tool: fpdns
        platforms: [linux, macos]
        command: "fpdns {host}"
        preferred: false
        notes: "Fingerprint DNS server implementation"
        requires_elevation: false

  - id: dns_zone_transfer
    name: DNS Zone Transfer (AXFR)
    description: Attempt full zone transfer to dump all DNS records
    order: 2
    timeout_seconds: 120
    commands:
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig axfr @{host}"
        preferred: true
        notes: "Attempt zone transfer without specifying domain"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig axfr @{host} {domain}"
        preferred: true
        notes: "Zone transfer for specific domain"
        requires_elevation: false
      - tool: fierce
        platforms: [linux, macos, windows]
        command: "fierce --domain {domain} --dns-servers {host}"
        preferred: true
        notes: "Attempt zone transfer and fall back to dictionary attack"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 53 --script dns-zone-transfer --script-args dns-zone-transfer.domain={domain} {host}"
        preferred: false
        notes: "Nmap DNS zone transfer script"
        requires_elevation: false

  - id: dns_record_enumeration
    name: DNS Record Enumeration
    description: Enumerate all DNS record types
    order: 3
    timeout_seconds: 120
    commands:
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig ANY @{host} {domain}"
        preferred: true
        notes: "Query all available DNS records (ANY query)"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig A @{host} {domain}"
        preferred: true
        notes: "Query A records (IPv4 addresses)"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig AAAA @{host} {domain}"
        preferred: true
        notes: "Query AAAA records (IPv6 addresses)"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig MX @{host} {domain}"
        preferred: true
        notes: "Query MX records (mail servers)"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig TXT @{host} {domain}"
        preferred: true
        notes: "Query TXT records (SPF, DKIM, DMARC, verification tokens)"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig NS @{host} {domain}"
        preferred: true
        notes: "Query NS records (authoritative nameservers)"
        requires_elevation: false

  - id: dns_subdomain_bruteforce
    name: DNS Subdomain Brute Force
    description: Brute force subdomains using wordlists
    order: 4
    timeout_seconds: 600
    commands:
      - tool: dnsenum
        platforms: [linux, macos]
        command: "dnsenum --dnsserver {host} --enum -p 0 -s 0 -o subdomains_{domain}.txt -f /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt {domain}"
        preferred: true
        notes: "Comprehensive subdomain enumeration"
        requires_elevation: false
      - tool: dnsrecon
        platforms: [linux, macos, windows]
        command: "dnsrecon -D /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -d {domain} -n {host}"
        preferred: true
        notes: "Subdomain brute forcing with dnsrecon"
        requires_elevation: false
      - tool: fierce
        platforms: [linux, macos, windows]
        command: "fierce --domain {domain} --subdomain-file /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt --dns-servers {host}"
        preferred: false
        notes: "Fierce subdomain scanner"
        requires_elevation: false

  - id: dns_reverse_lookup
    name: DNS Reverse Lookup Enumeration
    description: Reverse DNS lookups to discover additional hosts
    order: 5
    timeout_seconds: 300
    commands:
      - tool: dnsrecon
        platforms: [linux, macos, windows]
        command: "dnsrecon -r 127.0.0.0/24 -n {host} -d {domain}"
        preferred: true
        notes: "Reverse DNS brute force on 127.0.0.0/24 range"
        requires_elevation: false
      - tool: dnsrecon
        platforms: [linux, macos, windows]
        command: "dnsrecon -r {network}/{cidr} -n {host} -d {domain}"
        preferred: true
        notes: "Reverse DNS brute force on target network range"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig -x {ip} @{host}"
        preferred: false
        notes: "Reverse lookup for specific IP (PTR record)"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig -x 2a00:1450:400c:c06::93 @{host}"
        preferred: false
        notes: "Reverse IPv6 lookup"
        requires_elevation: false

  - id: dns_active_directory
    name: DNS Active Directory Enumeration
    description: Enumerate Active Directory SRV records
    order: 6
    timeout_seconds: 120
    commands:
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig -t _gc._tcp.{domain} @{host}"
        preferred: true
        notes: "Query Global Catalog servers"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig -t _ldap._tcp.{domain} @{host}"
        preferred: true
        notes: "Query LDAP servers"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig -t _kerberos._tcp.{domain} @{host}"
        preferred: true
        notes: "Query Kerberos KDC servers"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig -t _kpasswd._tcp.{domain} @{host}"
        preferred: true
        notes: "Query Kerberos password change servers"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap --script dns-srv-enum --script-args 'dns-srv-enum.domain={domain}' {host}"
        preferred: false
        notes: "Comprehensive SRV record enumeration"
        requires_elevation: false

  - id: dns_dnssec_enumeration
    name: DNSSEC Zone Walking
    description: Exploit DNSSEC to enumerate all records
    order: 7
    timeout_seconds: 180
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sSU -p53 --script dns-nsec-enum --script-args dns-nsec-enum.domains={domain} {host}"
        preferred: true
        notes: "DNSSEC NSEC record walking to enumerate subdomains"
        requires_elevation: false

  - id: dns_recursion_test
    name: DNS Recursion and DDoS Amplification
    description: Test for recursive queries and amplification attacks
    order: 8
    timeout_seconds: 60
    commands:
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig google.com A @{host}"
        preferred: true
        notes: "Test if DNS recursion is enabled (check for 'ra' flag)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/dns/dns_amp; set RHOSTS {host}; set RPORT 53; run; exit'"
        preferred: false
        notes: "Test DNS amplification attack potential"
        requires_elevation: false

  - id: dns_cache_snooping
    name: DNS Cache Snooping
    description: Enumerate cached DNS records to identify browsing history
    order: 9
    timeout_seconds: 120
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sU -p 53 --script dns-cache-snoop --script-args 'dns-cache-snoop.mode=timed,dns-cache-snoop.domains={domain_list}' {host}"
        preferred: true
        notes: "DNS cache snooping to discover visited domains"
        requires_elevation: false

metadata:
  tools:
    - dig
    - nmap
    - dnsenum
    - dnsrecon
    - fierce
    - fpdns
    - metasploit
  cves:
    - CVE-2020-25705  # BIND DNSSEC vulnerability
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-dns
    - http://bgp.he.net/
  techniques:
    - Zone transfer (AXFR/IXFR)
    - Subdomain brute forcing
    - Reverse DNS enumeration
    - Active Directory SRV enumeration
    - DNSSEC zone walking
    - DNS cache snooping
    - Recursion abuse for DDoS amplification
  batch_commands:
    zone_transfer: "parallel -j 10 'dig axfr @{} {domain}' :::: {targets_file}"
    dnsrecon: "dnsrecon -a -d {domain} -n {host}"
    metasploit_enum: "msfconsole -q -x 'use auxiliary/gather/enum_dns; set RHOSTS {host}; set RPORT 53; run; exit'"
