id: ftp_pentesting
name: FTP Penetration Testing (Port 21)
description: Comprehensive FTP service enumeration, authentication testing, and exploitation based on HackTricks methodology
category: enumeration
risk_level: medium
batch_compatible: true

triggers:
  - id: trigger_ftp_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [21, 2121] }
      protocol: { "$in": ["ftp", "tcp"] }
    required_count: 1
    priority: 4
    description: Triggers when FTP service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: ftp_banner_grab
    name: FTP Banner Grabbing
    description: Identify FTP server version and type
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p 21 {host} -oN ftp_banner_{host}.txt"
        preferred: true
        notes: "Extract FTP server version and banner"
        requires_elevation: false
      - tool: nc
        platforms: [linux, macos]
        command: "nc -vn {host} 21"
        preferred: false
        notes: "Simple banner grab with netcat"
        requires_elevation: false
      - tool: ftp
        platforms: [linux, macos, windows]
        command: "echo 'quit' | ftp {host}"
        preferred: false
        notes: "Connect and retrieve banner with FTP client"
        requires_elevation: false

  - id: ftp_anonymous_login
    name: Anonymous FTP Access
    description: Test for anonymous FTP login
    order: 2
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 21 --script ftp-anon {host}"
        preferred: true
        notes: "Check if anonymous login is enabled"
        requires_elevation: false
      - tool: ftp
        platforms: [linux, macos, windows]
        command: "echo -e 'USER anonymous\\nPASS anon@example.com\\nls\\nquit' | ftp -n {host}"
        preferred: false
        notes: "Manual anonymous login test"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/ftp/anonymous; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "Metasploit anonymous FTP scanner"
        requires_elevation: false

  - id: ftp_user_enum
    name: FTP User Enumeration
    description: Enumerate valid FTP users
    order: 3
    timeout_seconds: 180
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 21 --script ftp-brute --script-args userdb=/usr/share/wordlists/metasploit/unix_users.txt {host}"
        preferred: false
        notes: "Brute force users (use carefully)"
        requires_elevation: false
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L /usr/share/wordlists/metasploit/unix_users.txt -e nsr ftp://{host}"
        preferred: true
        notes: "User enumeration via null/same-as-username/reversed passwords"
        requires_elevation: false

  - id: ftp_bounce_scan
    name: FTP Bounce Attack
    description: Test for FTP bounce vulnerability
    order: 4
    timeout_seconds: 120
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -b {host} -Pn <target>"
        preferred: true
        notes: "FTP bounce scan (RFC 2228 violation)"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 21 --script ftp-bounce {host}"
        preferred: true
        notes: "Check if FTP server is vulnerable to bounce attack"
        requires_elevation: false

  - id: ftp_brute_force
    name: FTP Brute Force Authentication
    description: Attempt to brute force FTP credentials
    order: 5
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt ftp://{host} -t 4"
        preferred: true
        notes: "FTP credential brute forcing (may trigger IDS/account lockouts)"
        requires_elevation: false
      - tool: medusa
        platforms: [linux, macos, windows]
        command: "medusa -h {host} -U /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt -M ftp -t 4"
        preferred: false
        notes: "Alternative brute force tool"
        requires_elevation: false
      - tool: ncrack
        platforms: [linux, macos, windows]
        command: "ncrack -p 21 -user admin -P /usr/share/wordlists/rockyou.txt {host}"
        preferred: false
        notes: "Fast network authentication cracker"
        requires_elevation: false

  - id: ftp_vulnerabilities
    name: FTP Vulnerability Scanning
    description: Scan for known FTP vulnerabilities
    order: 6
    timeout_seconds: 180
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 21 --script ftp-* {host}"
        preferred: true
        notes: "Run all FTP NSE scripts"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 21 --script ftp-vuln-cve2010-4221,ftp-vsftpd-backdoor {host}"
        preferred: true
        notes: "Check for specific CVEs (vsftpd backdoor, ProFTPd)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/ftp/ftp_version; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "FTP version detection for exploit matching"
        requires_elevation: false

  - id: ftp_file_enum
    name: FTP File and Directory Enumeration
    description: List and download files from FTP server
    order: 7
    timeout_seconds: 300
    commands:
      - tool: wget
        platforms: [linux, macos]
        command: "wget -r ftp://anonymous:anon@{host}/"
        preferred: true
        notes: "Recursively download FTP contents (anonymous)"
        requires_elevation: false
      - tool: lftp
        platforms: [linux, macos]
        command: "lftp -u anonymous,anon {host} -e 'mirror / ./ftp_download_{host}; quit'"
        preferred: true
        notes: "Advanced FTP client with mirroring capabilities"
        requires_elevation: false
      - tool: ftp
        platforms: [linux, macos, windows]
        command: "echo -e 'USER anonymous\\nPASS anon@example.com\\nls -la\\nquit' | ftp -n {host}"
        preferred: false
        notes: "List all files including hidden"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - hydra
    - medusa
    - metasploit
    - wget
    - lftp
  cves:
    - CVE-2010-4221  # ProFTPd Telnet IAC
    - CVE-2011-2523  # vsftpd 2.3.4 backdoor
    - CVE-2015-3306  # ProFTPd mod_copy
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-ftp
    - https://owasp.org/www-community/attacks/FTP_Bounce_Attack
  batch_commands:
    nmap_anon: "nmap -p 21 --script ftp-anon -iL {targets_file} -oN ftp_anon_results.txt"
    hydra: "hydra -L users.txt -P passwords.txt ftp://{targets} -t 4"
