id: http_pentesting
name: HTTP/HTTPS Web Server Penetration Testing (Ports 80, 443)
description: Comprehensive web application enumeration, technology identification, directory brute forcing, and vulnerability scanning based on HackTricks methodology
category: enumeration
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_http_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [80, 443, 8080, 8443, 8000, 8888] }
      protocol: { "$in": ["http", "https", "tcp"] }
    required_count: 1
    priority: 7
    description: Triggers when HTTP/HTTPS service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: http_technology_identification
    name: Web Technology Identification
    description: Identify web server, frameworks, and technologies in use
    order: 1
    timeout_seconds: 120
    commands:
      - tool: whatweb
        platforms: [linux, macos, windows]
        command: "whatweb -a 3 {protocol}://{host}:{port}"
        preferred: true
        notes: "Aggressive web technology fingerprinting"
        requires_elevation: false
      - tool: webtech
        platforms: [linux, macos, windows]
        command: "webtech -u {protocol}://{host}:{port}"
        preferred: false
        notes: "Alternative technology identification tool"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p {port} --script http-enum,http-headers,http-methods,http-title {host}"
        preferred: true
        notes: "Nmap HTTP enumeration scripts"
        requires_elevation: false

  - id: http_waf_detection
    name: Web Application Firewall Detection
    description: Detect presence of WAF or security appliances
    order: 2
    timeout_seconds: 60
    commands:
      - tool: wafw00f
        platforms: [linux, macos, windows]
        command: "wafw00f {protocol}://{host}:{port}"
        preferred: true
        notes: "Identify Web Application Firewall"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script http-waf-detect,http-waf-fingerprint {host}"
        preferred: false
        notes: "Nmap WAF detection scripts"
        requires_elevation: false

  - id: http_ssl_tls_scan
    name: SSL/TLS Security Scan (HTTPS only)
    description: Comprehensive SSL/TLS vulnerability assessment
    order: 3
    timeout_seconds: 300
    commands:
      - tool: testssl
        platforms: [linux, macos]
        command: "testssl.sh --htmlfile testssl_{host}_{port}.html {host}:{port}"
        preferred: true
        notes: "Comprehensive SSL/TLS vulnerability scanner"
        requires_elevation: false
      - tool: sslscan
        platforms: [linux, macos, windows]
        command: "sslscan {host}:{port}"
        preferred: false
        notes: "SSL/TLS cipher and protocol scanner"
        requires_elevation: false
      - tool: sslyze
        platforms: [linux, macos, windows]
        command: "sslyze --regular {host}:{port}"
        preferred: false
        notes: "Fast SSL/TLS scanner"
        requires_elevation: false

  - id: http_initial_checks
    name: HTTP Initial Enumeration (robots.txt, sitemap.xml)
    description: Check for standard information disclosure files
    order: 4
    timeout_seconds: 60
    commands:
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -s {protocol}://{host}:{port}/robots.txt"
        preferred: true
        notes: "Check robots.txt for disallowed paths"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -s {protocol}://{host}:{port}/sitemap.xml"
        preferred: true
        notes: "Check sitemap.xml for URL enumeration"
        requires_elevation: false
      - tool: curl
        platforms: [linux, macos, windows]
        command: "curl -s {protocol}://{host}:{port}/.well-known/security.txt"
        preferred: false
        notes: "Check for security.txt disclosure"
        requires_elevation: false

  - id: http_spidering
    name: Web Application Spidering and Crawling
    description: Crawl web application to discover all endpoints
    order: 5
    timeout_seconds: 600
    commands:
      - tool: gospider
        platforms: [linux, macos, windows]
        command: "gospider -s {protocol}://{host}:{port} -o gospider_output -c 10 -d 5"
        preferred: true
        notes: "Fast Go-based web crawler with JS parsing"
        requires_elevation: false
      - tool: hakrawler
        platforms: [linux, macos, windows]
        command: "echo '{protocol}://{host}:{port}' | hakrawler -d 5"
        preferred: true
        notes: "Web crawler with Archive.org integration"
        requires_elevation: false
      - tool: katana
        platforms: [linux, macos, windows]
        command: "katana -u {protocol}://{host}:{port} -d 5 -jc -kf all -o katana_urls.txt"
        preferred: true
        notes: "Advanced web crawler from ProjectDiscovery"
        requires_elevation: false

  - id: http_directory_bruteforce
    name: Directory and File Brute Forcing
    description: Discover hidden directories and files
    order: 6
    timeout_seconds: 900
    commands:
      - tool: ffuf
        platforms: [linux, macos, windows]
        command: "ffuf -c -w /usr/share/wordlists/dirb/common.txt -u {protocol}://{host}:{port}/FUZZ -mc 200,204,301,302,307,401,403 -o ffuf_results.json"
        preferred: true
        notes: "Fast web fuzzer for directory enumeration"
        requires_elevation: false
      - tool: feroxbuster
        platforms: [linux, macos, windows]
        command: "feroxbuster -u {protocol}://{host}:{port} -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -x php,asp,aspx,jsp,html,js -t 50"
        preferred: true
        notes: "Recursive directory brute forcer with auto-tuning"
        requires_elevation: false
      - tool: gobuster
        platforms: [linux, macos, windows]
        command: "gobuster dir -u {protocol}://{host}:{port} -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -x php,html,txt -t 50"
        preferred: false
        notes: "Go-based directory/file enumeration"
        requires_elevation: false
      - tool: dirsearch
        platforms: [linux, macos, windows]
        command: "dirsearch -u {protocol}://{host}:{port} -e php,asp,aspx,jsp,html,js -t 50 --random-agent"
        preferred: false
        notes: "Python-based recursive directory scanner"
        requires_elevation: false

  - id: http_cms_detection
    name: CMS Detection and Scanning
    description: Identify and scan common CMS platforms
    order: 7
    timeout_seconds: 600
    commands:
      - tool: wpscan
        platforms: [linux, macos, windows]
        command: "wpscan --url {protocol}://{host}:{port} --enumerate ap,at,cb,dbe,u --random-user-agent --api-token {wpscan_api_token}"
        preferred: true
        notes: "WordPress vulnerability scanner"
        requires_elevation: false
      - tool: joomscan
        platforms: [linux, macos, windows]
        command: "joomscan -u {protocol}://{host}:{port} --enumerate-components"
        preferred: false
        notes: "Joomla vulnerability scanner"
        requires_elevation: false
      - tool: droopescan
        platforms: [linux, macos, windows]
        command: "droopescan scan drupal -u {protocol}://{host}:{port}"
        preferred: false
        notes: "Drupal/Joomla/Moodle/Silverstripe scanner"
        requires_elevation: false

  - id: http_vulnerability_scanning
    name: HTTP Vulnerability Scanning
    description: Automated vulnerability scanning with Nikto and Nuclei
    order: 8
    timeout_seconds: 1200
    commands:
      - tool: nikto
        platforms: [linux, macos, windows]
        command: "nikto -h {protocol}://{host}:{port} -C all -output nikto_{host}_{port}.txt"
        preferred: true
        notes: "Comprehensive web server vulnerability scanner"
        requires_elevation: false
      - tool: nuclei
        platforms: [linux, macos, windows]
        command: "nuclei -u {protocol}://{host}:{port} -severity critical,high,medium -o nuclei_{host}_{port}.txt"
        preferred: true
        notes: "Template-based vulnerability scanner (10000+ templates)"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script='http* and not (brute or dos or fuzzer)' {host} -oN nmap_http_{host}.txt"
        preferred: false
        notes: "Nmap HTTP vulnerability scripts"
        requires_elevation: false

  - id: http_parameter_discovery
    name: Hidden Parameter Discovery
    description: Discover hidden GET/POST parameters
    order: 9
    timeout_seconds: 300
    commands:
      - tool: arjun
        platforms: [linux, macos, windows]
        command: "arjun -u {protocol}://{host}:{port}/endpoint -oJ arjun_params.json"
        preferred: true
        notes: "HTTP parameter discovery tool"
        requires_elevation: false
      - tool: paramspider
        platforms: [linux, macos, windows]
        command: "paramspider -d {host} --level high -o paramspider_output.txt"
        preferred: false
        notes: "Discover parameters from web archives"
        requires_elevation: false

  - id: http_backup_file_check
    name: Backup File Discovery
    description: Search for backup files and source code disclosure
    order: 10
    timeout_seconds: 300
    commands:
      - tool: bfac
        platforms: [linux, macos, windows]
        command: "bfac --url {protocol}://{host}:{port} --level 4"
        preferred: true
        notes: "Backup file artifact checker"
        requires_elevation: false
      - tool: ffuf
        platforms: [linux, macos, windows]
        command: "ffuf -w /usr/share/seclists/Discovery/Web-Content/CommonBackupExtensions.txt -u {protocol}://{host}:{port}/index.phpFUZZ -mc 200"
        preferred: false
        notes: "Fuzz for backup file extensions"
        requires_elevation: false

metadata:
  tools:
    - whatweb
    - wafw00f
    - testssl
    - nikto
    - nuclei
    - ffuf
    - feroxbuster
    - gobuster
    - gospider
    - hakrawler
    - katana
    - wpscan
    - joomscan
    - droopescan
    - arjun
    - bfac
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-web
    - https://github.com/danielmiessler/SecLists
    - https://github.com/projectdiscovery/nuclei-templates
    - https://owasp.org/www-project-web-security-testing-guide/
  techniques:
    - Technology fingerprinting
    - WAF detection and bypass
    - SSL/TLS vulnerability assessment
    - Directory and file enumeration
    - Web application spidering
    - CMS identification and scanning
    - Backup file discovery
    - Hidden parameter discovery
    - Automated vulnerability scanning
    - Information disclosure via robots.txt/sitemap
  batch_commands:
    quick_scan: "parallel -j 5 'nikto -h {} && gobuster dir -u {} -w /usr/share/wordlists/dirb/common.txt' :::: {targets_file}"
    nuclei_scan: "nuclei -l {targets_file} -severity critical,high,medium -o nuclei_results.txt"
    tech_id: "parallel -j 10 'whatweb -a 3 {}' :::: {targets_file}"
  notes: |
    HTTP/HTTPS is the most common service and has the widest attack surface.

    METHODOLOGY WORKFLOW:
    1. Identify technologies (whatweb, nmap)
    2. Check for WAF (wafw00f)
    3. Test SSL/TLS if HTTPS (testssl.sh)
    4. Enumerate standard files (robots.txt, sitemap.xml)
    5. Spider the application (gospider, hakrawler, katana)
    6. Directory brute force (feroxbuster, ffuf)
    7. CMS detection and scanning (wpscan, joomscan)
    8. Vulnerability scanning (nikto, nuclei)
    9. Parameter discovery (arjun)
    10. Backup file hunting (bfac)

    COMMON CMS PLATFORMS:
    - WordPress: wpscan (most common)
    - Joomla: joomscan
    - Drupal: droopescan
    - Moodle: droopescan
    - Magento: magescan

    DIRECTORY WORDLISTS (best to worst):
    - /usr/share/seclists/Discovery/Web-Content/raft-large-directories.txt
    - /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt
    - /usr/share/wordlists/dirb/common.txt
    - Custom wordlists from Assetnote, SecLists

    SSL/TLS VULNERABILITIES TO CHECK:
    - Weak ciphers (RC4, DES, 3DES)
    - SSLv2, SSLv3, TLS 1.0, TLS 1.1 (deprecated)
    - BEAST, POODLE, Heartbleed, CRIME, BREACH
    - Certificate validation issues
    - Missing HSTS header

    WEB VULNERABILITIES (separate detailed testing):
    - SQL Injection
    - XSS (reflected, stored, DOM-based)
    - CSRF
    - SSRF
    - File upload
    - Authentication bypass
    - Authorization flaws
    - XXE
    - SSTI
    - Path traversal
    - Open redirects
    - Security misconfigurations

    PERFORMANCE TIPS:
    - Use batch scanning for multiple targets
    - Adjust thread count based on target responsiveness
    - Monitor for rate limiting and WAF blocking
    - Use random user agents to avoid fingerprinting
    - Respect robots.txt in production environments
