id: ldap_pentesting
name: LDAP Penetration Testing (Ports 389, 636, 3268, 3269)
description: Comprehensive LDAP enumeration, anonymous access testing, and authentication attacks based on HackTricks methodology
category: enumeration
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_ldap_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [389, 636, 3268, 3269] }
      protocol: { "$in": ["ldap", "ldaps", "tcp"] }
    required_count: 1
    priority: 5
    description: Triggers when LDAP service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: ldap_banner_grab
    name: LDAP Banner Grabbing
    description: Identify LDAP server version and capabilities
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -n -sV --script 'ldap* and not brute' {host} -p {port} -oN ldap_banner_{host}.txt"
        preferred: true
        notes: "Extract LDAP server version and supported features"
        requires_elevation: false
      - tool: ldapsearch
        platforms: [linux, macos]
        command: "ldapsearch -H ldap://{host} -x -s base -b '' '(objectClass=*)' '*' +"
        preferred: true
        notes: "Retrieve root DSE information"
        requires_elevation: false

  - id: ldap_anonymous_bind
    name: LDAP Anonymous Bind Test
    description: Test for anonymous/null bind access
    order: 2
    timeout_seconds: 60
    commands:
      - tool: ldapsearch
        platforms: [linux, macos]
        command: "ldapsearch -x -H ldap://{host} -D '' -w '' -b 'DC={domain},DC={tld}'"
        preferred: true
        notes: "Test anonymous bind with null credentials"
        requires_elevation: false
      - tool: netexec
        platforms: [linux, macos]
        command: "netexec ldap {host} -u '' -p '' --query '(objectClass=*)' ''"
        preferred: true
        notes: "Enumerate objects via null bind with NetExec"
        requires_elevation: false
      - tool: ldapsearch
        platforms: [linux, macos]
        command: "ldapsearch -H ldaps://{host}:636/ -x -s base -b '' '(objectClass=*)' '*' +"
        preferred: false
        notes: "Bypass TLS SNI check with arbitrary domain"
        requires_elevation: false

  - id: ldap_user_enumeration
    name: LDAP User Enumeration
    description: Enumerate users and groups via LDAP queries
    order: 3
    timeout_seconds: 180
    commands:
      - tool: ldapsearch
        platforms: [linux, macos]
        command: "ldapsearch -x -H ldap://{host} -D '{domain}\\{username}' -w '{password}' -b 'CN=Users,DC={domain},DC={tld}'"
        preferred: true
        notes: "Extract all users from Users container"
        requires_elevation: false
      - tool: windapsearch
        platforms: [linux, macos, windows]
        command: "python3 windapsearch.py --dc-ip {host} -u {username}@{domain} -p {password} --users"
        preferred: true
        notes: "Enumerate domain users with windapsearch"
        requires_elevation: false
      - tool: netexec
        platforms: [linux, macos]
        command: "netexec ldap {host} -u '' -p '' --query '(sAMAccountName=*)' '' | awk -F': ' '/sAMAccountName:/ {print $2}' | sort -u > users.txt"
        preferred: true
        notes: "Extract sAMAccountName list via null bind"
        requires_elevation: false

  - id: ldap_group_enumeration
    name: LDAP Group Enumeration
    description: Enumerate groups and privileged accounts
    order: 4
    timeout_seconds: 120
    commands:
      - tool: ldapsearch
        platforms: [linux, macos]
        command: "ldapsearch -x -H ldap://{host} -D '{domain}\\{username}' -w '{password}' -b 'CN=Domain Admins,CN=Users,DC={domain},DC={tld}'"
        preferred: true
        notes: "Extract Domain Admins group members"
        requires_elevation: false
      - tool: windapsearch
        platforms: [linux, macos, windows]
        command: "python3 windapsearch.py --dc-ip {host} -u {username}@{domain} -p {password} --da"
        preferred: true
        notes: "Enumerate Domain Admins"
        requires_elevation: false
      - tool: windapsearch
        platforms: [linux, macos, windows]
        command: "python3 windapsearch.py --dc-ip {host} -u {username}@{domain} -p {password} --privileged-users"
        preferred: false
        notes: "Enumerate all privileged users"
        requires_elevation: false

  - id: ldap_computer_enumeration
    name: LDAP Computer Enumeration
    description: Enumerate computers and workstations
    order: 5
    timeout_seconds: 120
    commands:
      - tool: ldapsearch
        platforms: [linux, macos]
        command: "ldapsearch -x -H ldap://{host} -D '{domain}\\{username}' -w '{password}' -b 'CN=Computers,DC={domain},DC={tld}'"
        preferred: true
        notes: "Extract all computers from Computers container"
        requires_elevation: false
      - tool: windapsearch
        platforms: [linux, macos, windows]
        command: "python3 windapsearch.py --dc-ip {host} -u {username}@{domain} -p {password} --computers"
        preferred: true
        notes: "Enumerate domain computers"
        requires_elevation: false

  - id: ldap_domain_dump
    name: LDAP Full Domain Dump
    description: Dump all domain information for offline analysis
    order: 6
    timeout_seconds: 300
    commands:
      - tool: ldapdomaindump
        platforms: [linux, macos]
        command: "ldapdomaindump {host} -u '{domain}\\{username}' -p '{password}' --no-json --no-grep -o ldap_dump_{host}"
        preferred: true
        notes: "Complete domain dump with ldapdomaindump"
        requires_elevation: false
      - tool: ldapsearch
        platforms: [linux, macos]
        command: "ldapsearch -x -H ldap://{host} -D '{domain}\\{username}' -w '{password}' -b 'DC={domain},DC={tld}' > ldap_full_dump_{host}.txt"
        preferred: false
        notes: "Full LDAP tree dump"
        requires_elevation: false

  - id: ldap_bloodhound
    name: LDAP BloodHound Collection
    description: Collect Active Directory data for BloodHound analysis
    order: 7
    timeout_seconds: 600
    commands:
      - tool: netexec
        platforms: [linux, macos]
        command: "netexec ldap {host} -u {username} -p {password} --bloodhound -c All -d {domain} --dns-server {host} --dns-tcp"
        preferred: true
        notes: "Complete BloodHound collection via NetExec"
        requires_elevation: false
      - tool: bloodhound-python
        platforms: [linux, macos, windows]
        command: "bloodhound-python -u {username}@{domain} -p {password} -ns {host} -d {domain} -c All"
        preferred: true
        notes: "BloodHound data collection (Python ingestor)"
        requires_elevation: false

  - id: ldap_password_attributes
    name: LDAP Password Attribute Search
    description: Search for passwords and sensitive attributes
    order: 8
    timeout_seconds: 180
    commands:
      - tool: ldapsearch
        platforms: [linux, macos]
        command: "ldapsearch -x -H ldap://{host} -D '{domain}\\{username}' -w '{password}' -b 'DC={domain},DC={tld}' '(&(objectClass=person))' userPassword | grep -i -A2 -B2 'userpas'"
        preferred: true
        notes: "Search for userPassword attributes (may be hashed)"
        requires_elevation: false
      - tool: ldapsearch
        platforms: [linux, macos]
        command: "ldapsearch -x -H ldap://{host} -D '{domain}\\{username}' -w '{password}' -b 'DC={domain},DC={tld}' '(description=*password*)'"
        preferred: false
        notes: "Search descriptions containing password keywords"
        requires_elevation: false

metadata:
  tools:
    - ldapsearch
    - nmap
    - netexec
    - windapsearch
    - ldapdomaindump
    - bloodhound
  cves:
    - CVE-2020-1472  # Zerologon - NetLogon elevation of privilege
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-ldap
    - https://github.com/ropnop/windapsearch
    - https://github.com/dirkjanm/ldapdomaindump
  techniques:
    - Anonymous/null bind enumeration
    - User and group enumeration
    - BloodHound data collection
    - SSH key injection via sshPublicKey attribute
    - Credential extraction from attributes
  batch_commands:
    ldapsearch_users: "parallel -j 10 'ldapsearch -x -H ldap://{} -b \"CN=Users,DC=domain,DC=local\" > ldap_users_{}.txt' :::: {targets_file}"
    netexec_bloodhound: "netexec ldap {targets} -u {username} -p {password} --bloodhound -c All -d {domain}"
