id: smtp_pentesting
name: SMTP Penetration Testing (Ports 25, 465, 587)
description: Comprehensive SMTP enumeration, user enumeration, relay testing, and email spoofing based on HackTricks methodology
category: enumeration
risk_level: medium
batch_compatible: true

triggers:
  - id: trigger_smtp_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [25, 465, 587] }
      protocol: { "$in": ["smtp", "smtps", "tcp"] }
    required_count: 1
    priority: 4
    description: Triggers when SMTP service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: smtp_banner_grab
    name: SMTP Banner Grabbing
    description: Identify SMTP server version and capabilities
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p {port} --script smtp-commands {host} -oN smtp_banner_{host}.txt"
        preferred: true
        notes: "Extract SMTP server version and supported commands"
        requires_elevation: false
      - tool: nc
        platforms: [linux, macos]
        command: "nc -vn {host} 25"
        preferred: false
        notes: "Simple SMTP banner grab with netcat"
        requires_elevation: false
      - tool: openssl
        platforms: [linux, macos, windows]
        command: "openssl s_client -crlf -connect {host}:465"
        preferred: false
        notes: "Connect to SMTPS (SSL/TLS on port 465)"
        requires_elevation: false
      - tool: openssl
        platforms: [linux, macos, windows]
        command: "openssl s_client -starttls smtp -crlf -connect {host}:587"
        preferred: false
        notes: "Connect to SMTP with STARTTLS (port 587)"
        requires_elevation: false

  - id: smtp_user_enumeration_vrfy
    name: SMTP User Enumeration (VRFY)
    description: Enumerate valid users via VRFY command
    order: 2
    timeout_seconds: 180
    commands:
      - tool: smtp-user-enum
        platforms: [linux, macos]
        command: "smtp-user-enum -M VRFY -U /usr/share/wordlists/metasploit/unix_users.txt -t {host}"
        preferred: true
        notes: "User enumeration via VRFY command"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script smtp-enum-users {host}"
        preferred: false
        notes: "Nmap SMTP user enumeration"
        requires_elevation: false

  - id: smtp_user_enumeration_rcpt
    name: SMTP User Enumeration (RCPT TO)
    description: Enumerate valid users via RCPT TO command
    order: 3
    timeout_seconds: 180
    commands:
      - tool: smtp-user-enum
        platforms: [linux, macos]
        command: "smtp-user-enum -M RCPT -U /usr/share/wordlists/metasploit/unix_users.txt -t {host}"
        preferred: true
        notes: "User enumeration via RCPT TO command"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/smtp/smtp_enum; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "Metasploit SMTP user enumeration"
        requires_elevation: false

  - id: smtp_user_enumeration_expn
    name: SMTP User Enumeration (EXPN)
    description: Enumerate mailing lists via EXPN command
    order: 4
    timeout_seconds: 120
    commands:
      - tool: smtp-user-enum
        platforms: [linux, macos]
        command: "smtp-user-enum -M EXPN -U /usr/share/wordlists/metasploit/unix_users.txt -t {host}"
        preferred: true
        notes: "Mailing list expansion via EXPN command"
        requires_elevation: false

  - id: smtp_open_relay
    name: SMTP Open Relay Test
    description: Test if SMTP server is configured as open relay
    order: 5
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script smtp-open-relay {host} -v"
        preferred: true
        notes: "Check if server allows mail relaying from external sources"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/smtp/smtp_relay; set RHOSTS {host}; set RPORT {port}; run; exit'"
        preferred: false
        notes: "Metasploit SMTP relay scanner"
        requires_elevation: false

  - id: smtp_ntlm_info
    name: SMTP NTLM Information Disclosure
    description: Extract internal information via NTLM authentication
    order: 6
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script smtp-ntlm-info {host}"
        preferred: true
        notes: "Extract Windows version and internal hostname via NTLM"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/smtp/smtp_ntlm_domain; set RHOSTS {host}; set RPORT {port}; run; exit'"
        preferred: false
        notes: "Metasploit NTLM information disclosure"
        requires_elevation: false

  - id: smtp_brute_force
    name: SMTP Authentication Brute Force
    description: Brute force SMTP authentication
    order: 7
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt smtp://{host} -t 4 -V"
        preferred: true
        notes: "SMTP authentication brute force with Hydra"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/smtp/smtp_login; set RHOSTS {host}; set USER_FILE users.txt; set PASS_FILE passwords.txt; run; exit'"
        preferred: false
        notes: "Metasploit SMTP login scanner"
        requires_elevation: false

  - id: smtp_vulnerabilities
    name: SMTP Vulnerability Scanning
    description: Scan for known SMTP vulnerabilities
    order: 8
    timeout_seconds: 180
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script smtp-vuln-cve2010-4344,smtp-vuln-cve2011-1720,smtp-vuln-cve2011-1764 {host}"
        preferred: true
        notes: "Check for known SMTP CVEs"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/smtp/smtp_version; set RHOSTS {host}; set RPORT {port}; run; exit'"
        preferred: false
        notes: "SMTP version detection for exploit matching"
        requires_elevation: false

  - id: smtp_email_harvesting
    name: SMTP Email Address Harvesting
    description: Send test emails to trigger NDN and harvest email headers
    order: 9
    timeout_seconds: 120
    commands:
      - tool: swaks
        platforms: [linux, macos]
        command: "swaks --to nonexistent@{domain} --from test@attacker.com --server {host} --header 'Subject: test'"
        preferred: true
        notes: "Send email to non-existent address to trigger NDN with headers"
        requires_elevation: false
      - tool: dig
        platforms: [linux, macos, windows]
        command: "dig +short mx {domain}"
        preferred: true
        notes: "Find MX servers for the organization"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - smtp-user-enum
    - hydra
    - metasploit
    - swaks
    - sendEmail
  cves:
    - CVE-2010-4344  # Exim SMTP DoS
    - CVE-2011-1720  # Postfix SMTP hardlink attack
    - CVE-2011-1764  # Exim DKIM verification bypass
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-smtp
    - https://seanthegeek.net/459/demystifying-dmarc/
  techniques:
    - User enumeration (VRFY, RCPT TO, EXPN)
    - Open relay exploitation
    - NTLM information disclosure
    - Email spoofing and phishing
    - SPF/DKIM/DMARC bypass
  batch_commands:
    nmap_enum: "nmap -p 25 --script smtp-enum-users -iL {targets_file} -oN smtp_users.txt"
    smtp_user_enum: "parallel -j 5 'smtp-user-enum -M VRFY -U users.txt -t {}' :::: {targets_file}"
