id: vnc_pentesting
name: VNC Penetration Testing (Ports 5800, 5900)
description: Comprehensive Virtual Network Computing enumeration, authentication bypass, and password cracking based on HackTricks methodology
category: enumeration
risk_level: medium
batch_compatible: true

triggers:
  - id: trigger_vnc_service
    type: asset_discovered
    asset_type: service
    required_properties:
      port: { "$in": [5800, 5801, 5900, 5901, 5902, 5903] }
      protocol: { "$in": ["vnc", "tcp"] }
    required_count: 1
    priority: 4
    description: Triggers when VNC service is discovered
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["host", "port"]

steps:
  - id: vnc_enumeration
    name: VNC Service Enumeration
    description: Identify VNC version and authentication requirements
    order: 1
    timeout_seconds: 60
    commands:
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sV --script vnc-info,vnc-title -p {port} {host} -oN vnc_enum_{host}.txt"
        preferred: true
        notes: "Extract VNC server information and desktop title"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -p {port} --script realvnc-auth-bypass {host}"
        preferred: true
        notes: "Check for RealVNC authentication bypass vulnerability"
        requires_elevation: false

  - id: vnc_no_auth_test
    name: VNC No Authentication Test
    description: Test for VNC servers with no authentication
    order: 2
    timeout_seconds: 60
    commands:
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/vnc/vnc_none_auth; set RHOSTS {host}; set RPORT {port}; run; exit'"
        preferred: true
        notes: "Check if VNC allows connections without authentication"
        requires_elevation: false
      - tool: vncviewer
        platforms: [linux, macos]
        command: "vncviewer {host}::{port}"
        preferred: false
        notes: "Attempt direct VNC connection (will prompt if password required)"
        requires_elevation: false

  - id: vnc_brute_force
    name: VNC Password Brute Force
    description: Brute force VNC authentication
    order: 3
    timeout_seconds: 600
    commands:
      - tool: hydra
        platforms: [linux, macos, windows]
        command: "hydra -P /usr/share/wordlists/rockyou.txt vnc://{host} -s {port} -t 4"
        preferred: true
        notes: "VNC password brute forcing with Hydra"
        requires_elevation: false
      - tool: medusa
        platforms: [linux, macos, windows]
        command: "medusa -h {host} -n {port} -P /usr/share/wordlists/rockyou.txt -M vnc -t 4"
        preferred: false
        notes: "Alternative VNC brute forcer"
        requires_elevation: false
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/scanner/vnc/vnc_login; set RHOSTS {host}; set RPORT {port}; set PASS_FILE passwords.txt; run; exit'"
        preferred: false
        notes: "Metasploit VNC login scanner"
        requires_elevation: false

  - id: vnc_password_extraction
    name: VNC Password File Extraction
    description: Extract and decrypt VNC password from config files
    order: 4
    timeout_seconds: 120
    commands:
      - tool: find
        platforms: [linux, macos]
        command: "find ~/.vnc /root/.vnc /home/*/.vnc -name 'passwd' 2>/dev/null"
        preferred: true
        notes: "Locate VNC password files on Linux/Mac"
        requires_elevation: false
      - tool: cmd
        platforms: [windows]
        command: "dir /s /b C:\\Users\\*\\AppData\\*.vnc"
        preferred: true
        notes: "Locate VNC password files on Windows"
        requires_elevation: false
      - tool: vncpwd
        platforms: [linux, macos]
        command: "vncpwd ~/.vnc/passwd"
        preferred: true
        notes: "Decrypt VNC password file (3DES encrypted)"
        requires_elevation: false

  - id: vnc_connect_with_password
    name: VNC Connection with Valid Password
    description: Connect to VNC service with known credentials
    order: 5
    timeout_seconds: 120
    commands:
      - tool: vncviewer
        platforms: [linux, macos]
        command: "vncviewer -passwd {password_file} {host}::{port}"
        preferred: true
        notes: "Connect to VNC with password file"
        requires_elevation: false
      - tool: vncviewer
        platforms: [linux, macos]
        command: "vncviewer {host}::{port}"
        preferred: false
        notes: "Interactive VNC connection (will prompt for password)"
        requires_elevation: false

  - id: vnc_screenshot_capture
    name: VNC Screenshot Capture
    description: Capture screenshots from VNC sessions
    order: 6
    timeout_seconds: 60
    commands:
      - tool: metasploit
        platforms: [linux, macos, windows]
        command: "msfconsole -q -x 'use auxiliary/admin/vnc/vnc_screenshot; set RHOSTS {host}; set RPORT {port}; set PASSWORD {password}; run; exit'"
        preferred: true
        notes: "Capture VNC screenshot with Metasploit"
        requires_elevation: false

metadata:
  tools:
    - nmap
    - vncviewer
    - hydra
    - medusa
    - metasploit
    - vncpwd
  cves:
    - CVE-2006-2369  # RealVNC authentication bypass
  references:
    - https://book.hacktricks.xyz/network-services-pentesting/pentesting-vnc
    - https://github.com/jeroennijhof/vncpwd
  techniques:
    - No authentication exploitation
    - Password brute forcing
    - VNC password file decryption (3DES)
    - Authentication bypass (RealVNC)
    - Screenshot capture
  batch_commands:
    nmap_scan: "nmap -sV --script vnc-info,vnc-title,realvnc-auth-bypass,vnc-brute -p 5900-5903 -iL {targets_file} -oN vnc_scan.txt"
    metasploit_scan: "msfconsole -q -x 'use auxiliary/scanner/vnc/vnc_none_auth; set RHOSTS file:{targets_file}; run; exit'"
  notes: |
    VNC (Virtual Network Computing) uses the Remote Frame Buffer (RFB) protocol
    to provide graphical remote desktop access.

    COMMON PORTS:
    - 5800, 5801: VNC over HTTP (web-based viewer)
    - 5900, 5901, 5902, 5903: Standard VNC display :0, :1, :2, :3

    SECURITY ISSUES:
    - Weak authentication (only password, no username)
    - Passwords encrypted with hardcoded 3DES key (easily reversible)
    - No built-in encryption (traffic sent in plaintext unless using VNC over SSH/TLS)
    - Some implementations allow no authentication
    - Default password files: ~/.vnc/passwd

    PASSWORD DECRYPTION:
    VNC passwords are encrypted with 3DES using a fixed key that was reverse-engineered.
    If you find a VNC password file (usually ~/.vnc/passwd), you can decrypt it using:
    - vncpwd (Linux/Mac): https://github.com/jeroennijhof/vncpwd
    - VNC Password Recovery (Windows): https://www.raymond.cc/blog/download/did/232/

    PRIVILEGE ESCALATION:
    - VNC servers often run with the privileges of the logged-in user
    - Compromising a VNC session = compromising that user account
    - Look for VNC sessions running as Administrator/root
