id: nac_credential_testing
name: NAC Credential Testing and Bypass
description: |
  Test credentials against NAC-protected network segments.
  Automatically batches multiple credential attempts for efficiency.
  This is the killer feature - realistic batched attack progression!
category: exploitation
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_nac_with_credentials
    type: asset_combination
    required_count: 2
    priority: 2
    description: Triggers when NAC-enabled network has available credentials
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["network_id", "credential_hash"]
      cooldown_seconds: 3600

  # Alternative trigger for property matching
  - id: trigger_nac_network_properties
    type: property_match
    asset_type: network_segment
    required_properties:
      nac_enabled: true
      access_level: blocked
    required_count: 1
    priority: 2
    description: Triggers when NAC is detected on a network segment
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["network_id"]

steps:
  - id: nac_credential_spray
    name: NAC Credential Spray
    description: Test credentials against NAC authentication
    command: "nac_bypass_tool --network {network_id} --credentials-file {credentials_file} --batch --threads 4"
    order: 1
    timeout_seconds: 1800

  - id: dot1x_bypass_attempt
    name: 802.1X Bypass Attempt
    description: Attempt various 802.1X bypass techniques
    command: "dot1x_bypass --interface eth0 --mac-spoof {authorized_mac} --username {username} --password {password}"
    order: 2
    timeout_seconds: 300

  - id: network_access_validation
    name: Validate Network Access
    description: Confirm successful bypass and document access level
    command: "ping -c 3 {gateway} && traceroute -m 5 {target_network}"
    order: 3
    timeout_seconds: 60

metadata:
  tools:
    - nac_bypass_tool
    - dot1x_bypass
  risk_warning: "High risk - May trigger IDS/IPS and security monitoring"
  batch_strategy: |
    When multiple credentials are available, this methodology automatically
    batches them into a single efficient credential spray operation rather
    than executing individually. This is realistic attacker behavior.
  expected_outcomes:
    - network_access_granted
    - nac_bypass_successful
    - access_level_upgraded
