/// AWS and GCP Resource Property Definitions
///
/// Comprehensive property schemas for AWS and GCP cloud resources
/// used in cloud penetration testing and security assessments.

class CloudAssetProperties {

  /// AWS EC2 Instance properties
  static const ec2InstanceProperties = {
    'instance_id': 'string',
    'instance_type': 'string',
    'ami_id': 'string',
    'state': 'string',
    'public_ip': 'string',
    'private_ip': 'string',
    'vpc_id': 'string',
    'subnet_id': 'string',
    'security_groups': 'objectList',
    'iam_role': 'string',
    'key_name': 'string',
    'user_data': 'string',
    'metadata_accessible': 'boolean',
    'imdsv2_required': 'boolean',
    'ebs_optimized': 'boolean',
    'monitoring_enabled': 'boolean',
    'ssm_managed': 'boolean',
    'patch_status': 'string',
    'tags': 'objectList',
    'region': 'string',
    'availability_zone': 'string',
    'platform': 'string',                  // Linux, Windows
    'architecture': 'string',              // x86_64, arm64
    'root_device_type': 'string',          // ebs, instance-store
    'virtualization_type': 'string',       // hvm, paravirtual
    'placement_group': 'string',
    'tenancy': 'string',                   // default, dedicated, host
    'source_dest_check': 'boolean',
    'hibernation_enabled': 'boolean',
    'nitro_enclaves': 'boolean',
    'cpu_options': 'objectList',
    'elastic_gpu': 'objectList',
    'elastic_inference': 'objectList',
    'network_interfaces': 'objectList',
    'block_device_mappings': 'objectList',
    'ebs_volumes': 'objectList',
    'volumes_encrypted': 'boolean',
    'vulnerability_findings': 'objectList',
  };

  /// AWS S3 Bucket properties
  static const s3BucketProperties = {
    'bucket_name': 'string',
    'region': 'string',
    'creation_date': 'dateTime',
    'public_access': 'boolean',
    'public_access_block': 'objectList',
    'bucket_policy': 'string',
    'acl': 'string',
    'cors_enabled': 'boolean',
    'cors_rules': 'objectList',
    'versioning': 'boolean',
    'mfa_delete': 'boolean',
    'encryption': 'string',                // None, AES256, aws:kms
    'kms_key': 'string',
    'logging_enabled': 'boolean',
    'logging_target_bucket': 'string',
    'website_hosting': 'boolean',
    'website_endpoint': 'string',
    'object_count': 'integer',
    'total_size_gb': 'double',
    'lifecycle_rules': 'objectList',
    'replication': 'objectList',
    'object_lock': 'boolean',
    'object_lock_configuration': 'objectList',
    'tags': 'objectList',
    'ownership_controls': 'string',
    'request_payment': 'string',
    'transfer_acceleration': 'boolean',
    'notifications': 'objectList',
    'inventory_configurations': 'objectList',
    'analytics_configurations': 'objectList',
    'metrics_configurations': 'objectList',
    'intelligent_tiering': 'boolean',
    'public_objects': 'objectList',
    'sensitive_data_found': 'objectList',
    'exposed_credentials': 'objectList',
    'access_keys_found': 'objectList',
  };

  /// AWS RDS Database properties
  static const rdsInstanceProperties = {
    'db_instance_id': 'string',
    'db_instance_arn': 'string',
    'engine': 'string',                    // mysql, postgres, mariadb, oracle, sqlserver
    'engine_version': 'string',
    'instance_class': 'string',
    'master_username': 'string',
    'endpoint': 'string',
    'port': 'integer',
    'publicly_accessible': 'boolean',
    'vpc_id': 'string',
    'subnet_group': 'string',
    'vpc_security_groups': 'objectList',
    'parameter_groups': 'objectList',
    'option_groups': 'objectList',
    'backup_retention': 'integer',
    'backup_window': 'string',
    'maintenance_window': 'string',
    'automated_backup_arn': 'string',
    'encrypted': 'boolean',
    'kms_key': 'string',
    'storage_type': 'string',              // gp2, gp3, io1, io2
    'storage_size_gb': 'integer',
    'max_allocated_storage': 'integer',
    'iops': 'integer',
    'multi_az': 'boolean',
    'read_replicas': 'stringList',
    'auto_minor_version_upgrade': 'boolean',
    'deletion_protection': 'boolean',
    'performance_insights': 'boolean',
    'performance_insights_retention': 'integer',
    'enhanced_monitoring': 'boolean',
    'monitoring_interval': 'integer',
    'cloudwatch_logs': 'objectList',
    'iam_database_authentication': 'boolean',
    'snapshot_identifier': 'string',
    'latest_restorable_time': 'dateTime',
    'license_model': 'string',
    'character_set': 'string',
    'tags': 'objectList',
    'region': 'string',
    'availability_zone': 'string',
    'status': 'string',
    'certificate_ca': 'string',
    'domain_memberships': 'objectList',
    'copy_tags_to_snapshot': 'boolean',
    'activity_stream': 'boolean',
    'vulnerability_findings': 'objectList',
    'weak_passwords': 'objectList',
    'public_snapshots': 'objectList',
  };

  /// AWS Lambda Function properties
  static const lambdaFunctionProperties = {
    'function_name': 'string',
    'function_arn': 'string',
    'runtime': 'string',                   // nodejs, python, java, go, ruby, dotnet
    'handler': 'string',
    'role': 'string',
    'description': 'string',
    'timeout': 'integer',
    'memory_size': 'integer',
    'code_size': 'integer',
    'code_sha256': 'string',
    'last_modified': 'dateTime',
    'version': 'string',
    'environment_variables': 'objectList',
    'vpc_config': 'objectList',
    'layers': 'stringList',
    'kms_key': 'string',
    'tracing': 'string',                   // Active, PassThrough
    'reserved_concurrent_executions': 'integer',
    'dead_letter_queue': 'string',
    'signing_profile_version': 'string',
    'signing_job': 'string',
    'code_repository_type': 'string',
    'code_repository_location': 'string',
    'image_uri': 'string',
    'image_config': 'objectList',
    'architectures': 'stringList',         // x86_64, arm64
    'package_type': 'string',              // Zip, Image
    'ephemeral_storage': 'integer',
    'file_system_configs': 'objectList',
    'tags': 'objectList',
    'region': 'string',
    'state': 'string',
    'state_reason': 'string',
    'last_update_status': 'string',
    'public_access': 'boolean',
    'resource_policy': 'string',
    'invoke_url': 'string',
    'aliases': 'stringList',
    'event_sources': 'objectList',
    'destinations': 'objectList',
    'secrets_in_env': 'objectList',
    'hardcoded_credentials': 'objectList',
    'overly_permissive_policy': 'boolean',
    'vulnerability_findings': 'objectList',
  };

  /// AWS IAM Role properties
  static const iamRoleProperties = {
    'role_name': 'string',
    'role_id': 'string',
    'role_arn': 'string',
    'path': 'string',
    'description': 'string',
    'assume_role_policy': 'string',
    'max_session_duration': 'integer',
    'permissions_boundary': 'string',
    'attached_policies': 'objectList',
    'inline_policies': 'objectList',
    'policy_count': 'integer',
    'creation_date': 'dateTime',
    'last_used': 'dateTime',
    'tags': 'objectList',
    'trusted_entities': 'stringList',
    'service_linked': 'boolean',
    'assumed_by_services': 'stringList',
    'assumed_by_principals': 'stringList',
    'ec2_instances': 'stringList',
    'lambda_functions': 'stringList',
    'admin_privileges': 'boolean',
    'privilege_escalation_possible': 'boolean',
    'dangerous_permissions': 'stringList',
    'resource_exposure': 'stringList',
    'unused_role': 'boolean',
  };

  /// AWS Secrets Manager properties
  static const awsSecretProperties = {
    'secret_name': 'string',
    'secret_arn': 'string',
    'description': 'string',
    'kms_key': 'string',
    'rotation_enabled': 'boolean',
    'rotation_lambda': 'string',
    'rotation_schedule': 'string',
    'last_rotated_date': 'dateTime',
    'last_accessed_date': 'dateTime',
    'created_date': 'dateTime',
    'deleted_date': 'dateTime',
    'tags': 'objectList',
    'region': 'string',
    'version_stages': 'stringList',
    'secret_type': 'string',               // Database, API Key, etc.
    'policy': 'string',
    'publicly_accessible': 'boolean',
    'cross_account_access': 'boolean',
    'no_rotation': 'boolean',
    'plaintext_accessible': 'boolean',
  };

  /// GCP Compute Instance properties
  static const computeInstanceProperties = {
    'instance_id': 'string',
    'instance_name': 'string',
    'machine_type': 'string',
    'zone': 'string',
    'region': 'string',
    'project_id': 'string',
    'status': 'string',                    // RUNNING, STOPPED, etc.
    'creation_timestamp': 'dateTime',
    'description': 'string',
    'tags': 'objectList',
    'labels': 'objectList',
    'network_interfaces': 'objectList',
    'external_ip': 'string',
    'internal_ip': 'string',
    'network_tier': 'string',              // PREMIUM, STANDARD
    'service_accounts': 'objectList',
    'scopes': 'stringList',
    'metadata': 'objectList',
    'ssh_keys': 'objectList',
    'os_login': 'boolean',
    'disks': 'objectList',
    'boot_disk': 'objectList',
    'disk_encrypted': 'boolean',
    'encryption_keys': 'objectList',
    'guest_accelerators': 'objectList',    // GPUs
    'min_cpu_platform': 'string',
    'scheduling': 'objectList',
    'preemptible': 'boolean',
    'automatic_restart': 'boolean',
    'on_host_maintenance': 'string',
    'shielded_instance_config': 'objectList',
    'shielded_instance': 'boolean',
    'confidential_instance': 'boolean',
    'can_ip_forward': 'boolean',
    'deletion_protection': 'boolean',
    'fingerprint': 'string',
    'self_link': 'string',
    'vulnerability_findings': 'objectList',
    'missing_patches': 'objectList',
  };

  /// GCP Cloud Storage Bucket properties
  static const cloudStorageBucketProperties = {
    'bucket_name': 'string',
    'project_id': 'string',
    'location': 'string',
    'location_type': 'string',             // region, dual-region, multi-region
    'storage_class': 'string',             // STANDARD, NEARLINE, COLDLINE, ARCHIVE
    'time_created': 'dateTime',
    'updated': 'dateTime',
    'metageneration': 'integer',
    'self_link': 'string',
    'labels': 'objectList',
    'website_config': 'objectList',
    'versioning': 'boolean',
    'lifecycle_rules': 'objectList',
    'cors_config': 'objectList',
    'default_event_based_hold': 'boolean',
    'retention_policy': 'objectList',
    'retention_period': 'integer',
    'retention_effective_time': 'dateTime',
    'encryption': 'string',
    'default_kms_key': 'string',
    'autoclass': 'objectList',
    'logging_enabled': 'boolean',
    'log_bucket': 'string',
    'log_object_prefix': 'string',
    'requester_pays': 'boolean',
    'public_access_prevention': 'boolean',
    'uniform_bucket_level_access': 'boolean',
    'access_control': 'string',            // uniform, fine-grained
    'iam_configuration': 'objectList',
    'iam_policy': 'objectList',
    'acl': 'objectList',
    'default_object_acl': 'objectList',
    'owner': 'string',
    'default_encryption': 'objectList',
    'notification_configs': 'objectList',
    'object_count': 'integer',
    'total_size_gb': 'double',
    'public_access': 'boolean',
    'public_objects': 'objectList',
    'all_users_access': 'boolean',
    'all_authenticated_users_access': 'boolean',
    'sensitive_data_found': 'objectList',
  };

  /// GCP Cloud SQL properties
  static const cloudSQLProperties = {
    'instance_name': 'string',
    'project_id': 'string',
    'connection_name': 'string',
    'database_version': 'string',          // MYSQL_8_0, POSTGRES_14, etc.
    'region': 'string',
    'tier': 'string',
    'state': 'string',
    'creation_time': 'dateTime',
    'self_link': 'string',
    'master_instance_name': 'string',
    'replica_names': 'stringList',
    'backend_type': 'string',              // SECOND_GEN, EXTERNAL
    'service_account': 'string',
    'ip_addresses': 'objectList',
    'public_ip': 'string',
    'private_ip': 'string',
    'ipv6_address': 'string',
    'connection_name_': 'string',
    'ssl_required': 'boolean',
    'server_ca_cert': 'objectList',
    'client_certs': 'objectList',
    'authorized_networks': 'objectList',
    'publicly_accessible': 'boolean',
    'private_network': 'string',
    'settings': 'objectList',
    'data_disk_type': 'string',
    'data_disk_size_gb': 'integer',
    'storage_auto_resize': 'boolean',
    'storage_auto_resize_limit': 'integer',
    'availability_type': 'string',         // ZONAL, REGIONAL
    'backup_configuration': 'objectList',
    'backup_enabled': 'boolean',
    'binary_log_enabled': 'boolean',
    'point_in_time_recovery': 'boolean',
    'transaction_log_retention': 'integer',
    'maintenance_window': 'objectList',
    'database_flags': 'objectList',
    'labels': 'objectList',
    'encryption_config': 'objectList',
    'disk_encrypted': 'boolean',
    'kms_key': 'string',
    'deletion_protection': 'boolean',
    'root_password': 'string',
    'database_users': 'objectList',
    'databases': 'stringList',
    'vulnerability_findings': 'objectList',
    'weak_passwords': 'objectList',
    'public_snapshots': 'objectList',
  };

  /// GCP Cloud Function properties
  static const cloudFunctionProperties = {
    'function_name': 'string',
    'project_id': 'string',
    'region': 'string',
    'description': 'string',
    'status': 'string',
    'entry_point': 'string',
    'runtime': 'string',                   // nodejs, python, go, java, ruby, php, dotnet
    'timeout': 'string',
    'available_memory_mb': 'integer',
    'service_account': 'string',
    'update_time': 'dateTime',
    'version_id': 'string',
    'labels': 'objectList',
    'environment_variables': 'objectList',
    'build_environment_variables': 'objectList',
    'network': 'string',
    'vpc_connector': 'string',
    'vpc_connector_egress': 'string',
    'ingress_settings': 'string',          // ALLOW_ALL, ALLOW_INTERNAL_ONLY, etc.
    'kms_key': 'string',
    'source_archive_url': 'string',
    'source_repository': 'objectList',
    'source_upload_url': 'string',
    'https_trigger': 'objectList',
    'event_trigger': 'objectList',
    'trigger_http': 'boolean',
    'trigger_url': 'string',
    'event_type': 'string',
    'event_resource': 'string',
    'max_instances': 'integer',
    'min_instances': 'integer',
    'build_id': 'string',
    'build_name': 'string',
    'secrets': 'objectList',
    'docker_registry': 'string',
    'docker_repository': 'string',
    'self_link': 'string',
    'public_access': 'boolean',
    'iam_policy': 'objectList',
    'all_users_invoker': 'boolean',
    'secrets_in_env': 'objectList',
    'hardcoded_credentials': 'objectList',
    'vulnerability_findings': 'objectList',
  };
}
