id: "nmap_discovery"
version: "1.0.0"
template_version: "1.0"
name: "Network Discovery and Scanning"
workstream: "Reconnaissance"
author: "Security Team"
created: "2024-01-01"
modified: "2024-01-01"
status: "active"
description: "Initial network discovery and port scanning"
tags: ["nmap", "discovery", "reconnaissance"]
risk_level: "low"

overview:
  purpose: "Discover live hosts and open services"
  scope: "All authorized network ranges"
  prerequisites:
    - "Network access"
    - "Authorized IP ranges"
  category: "Discovery"

triggers:
  - name: "New Network Segment"
    description: "New network segment discovered - perform discovery scan"
    conditions:
      asset_type: "networkSegment"
      properties:
        "scanned": "false"
    priority: 100
    batch_capable: false
    individual_command: "nmap -sn <subnet>"
    command_variants:
      quick: "nmap -sn -T4 <subnet>"
      thorough: "nmap -sn -PS21,22,25,80,443,3389,8080 -PA80,443 -PU53,161 <subnet>"
    expected_property_updates: ["live_hosts", "scanned"]
    expected_asset_discovery: ["host"]
    tags: ["discovery", "ping_sweep"]
    enabled: true

  - name: "Live Host Discovered"
    description: "Host is alive - perform port scan"
    conditions:
      asset_type: "host"
      properties:
        "alive": "true"
        "ports_scanned": "false"
    priority: 90
    batch_capable: true
    batch_criteria: "subnet"
    max_batch_size: 20
    batch_command: "nmap -sS -sV -p- <subnet>"
    individual_command: "nmap -sS -sV -p- <target_ip>"
    expected_property_updates: ["open_ports", "services", "os_detection"]
    expected_asset_discovery: ["service"]
    tags: ["port_scan", "service_detection"]
    enabled: true

procedures:
  - id: "initial_discovery"
    name: "Initial Network Discovery"
    description: "Discover live hosts in network"
    commands:
      - "nmap -sn <subnet>"
      - "arp-scan -l"
      - "netdiscover -r <subnet>"

findings:
  - id: "DISC-001"
    title: "Unnecessary Services Exposed"
    severity: "low"
    description: "Non-essential services are accessible"
    remediation: "Disable or filter unnecessary services"