id: dhcp_autoconfiguration
name: DHCP Auto-Configuration
category: Physical Network Access
priority: critical
description: Connect to the network and automatically obtain IP configuration via DHCP to gain initial network access.
detailed_description: |
  Attempt to obtain network access through DHCP auto-configuration. This technique connects to the network
  and automatically requests IP configuration to gain initial access without authentication.

required_conditions:
  - physical_access
  - no_port_security

optional_conditions:
  - no_nac_protection
  - dhcp_enabled

tools:
  - name: dhclient
    description: Linux DHCP client
    platform: linux
  - name: ipconfig
    description: Windows network configuration
    platform: windows
  - name: tcpdump
    description: Network packet analyzer
    platform: linux

phases:
  - name: preparation
    steps:
      - id: identify_interface
        action: Identify network interface
        command: ip link show
        alternatives:
          - shell: windows_cmd
            command: ipconfig /all
          - shell: macos
            command: ifconfig -a

      - id: release_existing
        action: Release existing DHCP lease
        command: sudo dhclient -r {interface_name}
        alternatives:
          - shell: windows_cmd
            command: ipconfig /release {adapter_name}

  - name: execution
    steps:
      - id: monitor_traffic
        action: Monitor DHCP traffic
        command: sudo tcpdump -i {interface_name} -n port 67 and port 68
        optional: true

      - id: request_dhcp
        action: Request DHCP configuration
        command: sudo dhclient -v {interface_name}
        alternatives:
          - shell: windows_cmd
            command: ipconfig /renew {adapter_name}
          - shell: macos
            command: sudo ipconfig set {interface_name} DHCP
        expected_output: |
          DHCPREQUEST
          DHCPACK
          bound to {ip_address}

      - id: verify_config
        action: Verify network configuration
        command: ip addr show {interface_name}
        alternatives:
          - shell: windows_cmd
            command: ipconfig /all

  - name: discovery
    steps:
      - id: extract_network_info
        action: Extract network information
        command: ip route show
        output_variables:
          - gateway_ip
          - subnet_range
          - dns_servers

      - id: identify_domain
        action: Check for domain information
        command: cat /etc/resolv.conf | grep domain
        alternatives:
          - shell: windows_cmd
            command: ipconfig /all | findstr "DNS Domain"

triggers:
  on_complete:
    - methodology: network_discovery
      condition: ip_obtained
    - methodology: port_scanning
      condition: network_access

findings:
  - id: no_network_segmentation
    title: No Network Segmentation for Unauthorized Devices
    severity: medium
    description: DHCP provides network access without device authentication

  - id: sensitive_info_leak
    title: DHCP Provides Sensitive Information
    severity: low
    description: DHCP response reveals DNS servers, domain name, and network topology

  - id: no_nac
    title: No NAC Implementation
    severity: high
    description: Network allows unauthorized devices to obtain IP addresses

issues:
  - symptom: DHCP request times out
    severity: medium
    causes:
      - DHCP server not available
      - Port security enabled
      - MAC filtering active
    resolutions:
      - Try static IP configuration
      - Attempt MAC spoofing
      - Check for 802.1X requirements

  - symptom: Limited access VLAN assigned
    severity: low
    causes:
      - NAC assigns guest/quarantine VLAN
      - Unknown MAC address policy
    resolutions:
      - Try MAC spoofing of known device
      - Attempt VLAN hopping
      - Look for authentication portal

cleanup:
  - priority: medium
    action: Release DHCP lease
    command: sudo dhclient -r {interface_name}

  - priority: low
    action: Clear DHCP client cache
    command: sudo rm /var/lib/dhcp/dhclient.leases

outcome_analysis:
  success_indicators:
    - IP address obtained
    - Gateway reachable
    - DNS resolution working

  failure_indicators:
    - No DHCP response
    - Authentication required
    - Quarantine VLAN assigned