id: smb_auth_test
name: SMB Authentication Testing
version: 1.0.0
category: exploitation
description: Test SMB authentication using available credentials
rationale: SMB services often use weak or default credentials that can be exploited
risk_level: medium
stealth_level: active
estimated_duration_minutes: 15

triggers:
  - id: smb_service_credential_available
    type: service_detected
    description: Trigger when SMB service is detected and credentials are available
    priority: 10
    conditions:
      service: smb
      port: 445
      credentials:
        allow_empty: false
    deduplication:
      strategy: signature_based
      signature_fields: [host, port, credential_id]
      cooldown_seconds: 3600
      max_executions: 3

execution_methods:
  - id: test_smb_auth
    name: Test SMB Authentication
    description: Attempt to authenticate to SMB service using available credentials
    type: command
    command: smbclient -L {{HOST}} -U {{CREDENTIAL_USER}}%{{CREDENTIAL_PASS}}
    variants:
      - condition: CREDENTIAL_DOMAIN exists
        command: smbclient -L {{HOST}} -U {{CREDENTIAL_DOMAIN}}/{{CREDENTIAL_USER}}%{{CREDENTIAL_PASS}}
        description: Use domain authentication
      - condition: PORT != "445"
        command: smbclient -L {{HOST}} -p {{PORT}} -U {{CREDENTIAL_USER}}%{{CREDENTIAL_PASS}}
        description: Use custom port
    expected_outputs:
      - type: authentication_success
        parser: text
        success_indicators:
          - "Sharename"
          - "Type"
          - "Comment"
        failure_indicators:
          - "NT_STATUS_LOGON_FAILURE"
          - "NT_STATUS_ACCESS_DENIED"
          - "Connection failed"
    asset_discovery:
      - pattern: "\\s+(\\w+)\\s+Disk\\s+"
        asset_type: smb_share
        confidence: 0.9
        metadata:
          type: disk_share
      - pattern: "\\s+(\\w+)\\s+Printer\\s+"
        asset_type: smb_share
        confidence: 0.8
        metadata:
          type: printer_share
    timeout_seconds: 30

  - id: enum_smb_shares
    name: Enumerate SMB Shares
    description: List available SMB shares after successful authentication
    type: command
    command: smbclient -L {{HOST}} -U {{CREDENTIAL_USER}}%{{CREDENTIAL_PASS}} | grep -E "Disk|Printer"
    expected_outputs:
      - type: share_enumeration
        parser: text
        success_indicators:
          - "Disk"
          - "Printer"
    timeout_seconds: 20

expected_asset_types:
  - smb_share
  - smb_service

suppression_options:
  - scope: host
    description: Skip SMB testing for this host
    conditions:
      - host_blacklisted
  - scope: credential
    description: Skip this credential set
    conditions:
      - credential_failed_multiple_times

next_methodologies:
  - smb_share_enumeration
  - smb_null_session_test